In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 데이터프레임 불러오기
path = '/content/drive/MyDrive/딥다이브/2강/네이버 뉴스_삼성_2월.csv'
df = pd.read_csv(path)

In [ ]:
# 데이터 정보 확인하기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45721 entries, 0 to 45720
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   제목         45721 non-null  object
 1   언론사        45721 non-null  object
 2   날짜         45721 non-null  object
 3   URL        45721 non-null  object
 4   네이버뉴스_URL  21866 non-null  object
dtypes: object(5)
memory usage: 1.7+ MB

In [ ]:
# 데이터 예시
df.head(10)

,제목,언론사,날짜,URL,네이버뉴스_URL
0,"‘1.1㎏’ 윤슬이, 수술없이 심장병 치료",중앙일보,2023.02.02.,https://www.joongang.co.kr/article/25137604,https://n.news.naver.com/mnews/article/025/000...
1,[부고] 안원보씨 外,중앙일보,2023.02.02.,https://www.joongang.co.kr/article/25137600,https://n.news.naver.com/mnews/article/025/000...
2,"[사설] 첫달 127억弗 무역적자, 수출 위기 극복 위해 ‘경제워룸’ 가동하라",서울경제언론사 선정,2023.02.02.,https://www.sedaily.com/NewsView/29LLD5CEX1,https://n.news.naver.com/mnews/article/011/000...
3,"""이런 분위기 몇 년 만인지…"" 패배의식 걷어낸 이적생 슈터",엑스포츠뉴스,2023.02.02.,https://www.xportsnews.com/article/1683280,https://sports.news.naver.com/news.nhn?oid=311...
4,"“자고 갈 면목이 없더라” 1순위 출신 22세 유망주, 올스타전 끝나고 야간 훈련 ...",MK스포츠,2023.02.02.,https://www.mk.co.kr/article/10627317,https://sports.news.naver.com/news.nhn?oid=410...
5,"뉴욕증시 비트코인 흔들 FOMC 금리인상 중단 ""시기상조"" 제롬 파월 연준 피벗 부인",글로벌이코노믹,2023.02.02.,http://www.g-enews.com/ko-kr/news/article/news...,NaN
6,유니켐 주가 기세등등...자동차시드 등 판매 증가 주목,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN
7,에코프로비엠 매수 몰리며 주가 두둥실...외국인과 기관 '줍줍',핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN
8,다믈멀티미디어 주가 돌연 급등랠리... 최대주주 변경이 뭐길래?,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN
9,에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN

In [ ]:
# URL 기준 중복값 확인 .duplicated -> true or false
df[df.duplicated(subset = 'URL')]

,제목,언론사,날짜,URL,네이버뉴스_URL
56,"삼성전자, 신규 프리미엄 노트북 '갤럭시 북3 울트라' 공개",뉴스핌,2023.02.02.,http://www.newspim.com/news/view/20230201001211,NaN
60,2억화소 폰으로 밤하늘 성운·은하까지 찍는다…카메라의 혁신,디지털타임스언론사 선정,2023.02.02.,http://www.dt.co.kr/contents.html?article_no=2...,https://n.news.naver.com/mnews/article/029/000...
61,삼성 갤럭시북3 삼총사 발표…첫 '울트라' 노트북 22일 출시,뉴스1,2023.02.02.,https://www.news1.kr/articles/4940341,https://n.news.naver.com/mnews/article/421/000...
70,"삼성전자, 괴물카메라 탑재한 ‘갤럭시 S23 시리즈’ 공개",부산일보언론사 선정,2023.02.02.,https://www.busan.com/view/busan/view.php?code...,https://n.news.naver.com/mnews/article/082/000...
72,"[삼성 갤럭시 언팩] “갤S23, AI로 게이밍 성능 개선”",파이낸셜뉴스언론사 선정,2023.02.02.,http://www.fnnews.com/news/202302011055452971,https://n.news.naver.com/mnews/article/014/000...
...,...,...,...,...,...
45520,대기업 제재 해마다 증가...5년 새 과태료·벌금·과징금 등 2.2조원,베타뉴스,2023.02.28.,http://www.betanews.net:8080/article/1393543.html,NaN
45570,[포토]멋진 무대 선보이는 펜타곤,이데일리,2023.02.28.,http://starin.edaily.co.kr/news/newspath.asp?n...,https://n.news.naver.com/mnews/article/018/000...
45650,"[MWC '23] 한종희 삼성전자 부회장 ""다음엔 갤럭시로 금성 찍어보자""",EBN,2023.02.28.,https://www.ebn.co.kr/news/view/1568743/?sc=Naver,NaN
45670,"[사진]김태훈,'호쾌한 2루타'",OSEN,2023.02.28.,http://www.osen.co.kr/article/G1112051380,https://sports.news.naver.com/news.nhn?oid=109...
45690,"[사진]김진욱,'무조건 막는다'",OSEN,2023.02.28.,http://www.osen.co.kr/article/G1112051395,https://sports.news.naver.com/news.nhn?oid=109...

In [ ]:
# URL 기준 중복값 제거
df.drop_duplicates(subset = 'URL', keep = 'first', inplace = True)

In [ ]:
# 인덱스 재설정
df.reset_index(drop = True, inplace = True)

In [ ]:
# Konlpy 불러오기
!pip install konlpy

from konlpy.tag import Okt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 26.5 MB/s eta 0:00:00
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading JPype1-1.4.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (465 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 32.1 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.2)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.22.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (23.1)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.1 konlpy-0.6.0

In [ ]:
# Okt 불러오기
okt = Okt()

In [ ]:
# 명사 중심의 토큰화
df['단어'] = df['제목'].map(okt.nouns)

In [ ]:
df

,제목,언론사,날짜,URL,네이버뉴스_URL,단어
0,"‘1.1㎏’ 윤슬이, 수술없이 심장병 치료",중앙일보,2023.02.02.,https://www.joongang.co.kr/article/25137604,https://n.news.naver.com/mnews/article/025/000...,"[윤슬, 수술, 심장병, 치료]"
1,[부고] 안원보씨 外,중앙일보,2023.02.02.,https://www.joongang.co.kr/article/25137600,https://n.news.naver.com/mnews/article/025/000...,"[부고, 안원, 보]"
2,"[사설] 첫달 127억弗 무역적자, 수출 위기 극복 위해 ‘경제워룸’ 가동하라",서울경제언론사 선정,2023.02.02.,https://www.sedaily.com/NewsView/29LLD5CEX1,https://n.news.naver.com/mnews/article/011/000...,"[사설, 달, 무역적자, 수출, 위기, 극복, 위해, 경제, 워룸, 가동]"
3,"""이런 분위기 몇 년 만인지…"" 패배의식 걷어낸 이적생 슈터",엑스포츠뉴스,2023.02.02.,https://www.xportsnews.com/article/1683280,https://sports.news.naver.com/news.nhn?oid=311...,"[분위기, 몇, 년, 만인, 패배, 의식, 이적, 생, 슈터]"
4,"“자고 갈 면목이 없더라” 1순위 출신 22세 유망주, 올스타전 끝나고 야간 훈련 ...",MK스포츠,2023.02.02.,https://www.mk.co.kr/article/10627317,https://sports.news.naver.com/news.nhn?oid=410...,"[자고, 면목, 순위, 출신, 세, 유망, 주, 올스타전, 야간, 훈련, 자청, 이..."
...,...,...,...,...,...,...
44201,"스카이플레이, 모비소프트와 HTML 게임 온보딩 계약 체결",더게임스데일리,2023.02.28.,http://www.tgdaily.co.kr/news/articleView.html...,NaN,"[스카이, 플레이, 모비, 소프트, 게임, 온보딩, 계약, 체결]"
44202,"'K리그1 복귀' 광주, 2023 홈개막전서 다양한 행사 준비",스포츠투데이,2023.02.28.,http://www.stoo.com/article.php?aid=85675991809,NaN,"[리그, 복귀, 광주, 홈, 개막전, 행사, 준비]"
44203,"양향자 국회의원 ""미래 모빌리티 기술에 걸맞은 입법·정책 뒷받침 절실, 핵심 인재 ...",에이빙뉴스,2023.02.28.,http://kr.aving.net/news/articleView.html?idxn...,NaN,"[향, 국회의원, 미래, 모빌리티, 기술, 걸, 입법, 정책, 뒷받침, 절실, 핵심..."
44204,"美, 반도체 보조금 조건으로 시설 접근권-초과이익 공유 요구",동아일보언론사 선정,2023.02.28.,https://www.donga.com/news/Inter/article/all/2...,https://n.news.naver.com/mnews/article/020/000...,"[반도체, 보조금, 조건, 시설, 접근권, 초과, 이익, 공유, 요구]"
44205,"인천시, 교통비 월 최대 4만원 환급받는 '알뜰교통카드' 사용 편리해진다",경인매일,2023.02.28.,https://www.kmaeil.com/news/articleView.html?i...,NaN,"[인천, 시, 교통비, 월, 최대, 환급, 알뜰, 교통카드, 사용]"

In [ ]:
# 단어 리스트 만들기
word_list = sum(df['단어'], []); word_list

['윤슬',
 '수술',
 '심장병',
 '치료',
 '부고',
 '안원',
 '보',
 '사설',
 '달',
 '무역적자',
 '수출',
 '위기',
 '극복',
 '위해',
 '경제',
 '워룸',
 '가동',
 '분위기',
 '몇',
 '년',
 '만인',
 '패배',
 '의식',
 '이적',
 '생',
 '슈터',
 '자고',
 '면목',
 '순위',
 '출신',
 '세',
 '유망',
 '주',
 '올스타전',
 '야간',
 '훈련',
 '자청',
 '이유',
 '인터뷰',
 '뉴욕증시',
 '비트코인',
 '금리',
 '인상',
 '중단',
 '시기상조',
 '제롬',
 '파월',
 '준',
 '피벗',
 '부인',
 '유니',
 '켐',
 '주가',
 '기세',
 '등등',
 '자동차',
 '시드',
 '등',
 '판매',
 '증가',
 '주목',
 '에코',
 '프로비',
 '엠',
 '매수',
 '몰리',
 '주가',
 '두둥실',
 '외국인',
 '기관',
 '다믈',
 '멀티미디어',
 '주가',
 '돌연',
 '급등',
 '랠리',
 '최대',
 '주주',
 '변경',
 '뭐길',
 '에코',
 '프로비',
 '엠',
 '하이닉스',
 '삼성',
 '셀트리온',
 '현대',
 '로템',
 '외국인',
 '매수',
 '거래',
 '활발',
 '추정',
 '기업가',
 '거',
 '인증',
 '투병',
 '최',
 '신',
 '전',
 '여자',
 '농구',
 '선수',
 '김영희',
 '별세',
 '곳',
 '중',
 '곳',
 '이하',
 '실적',
 '공포',
 '현실',
 '브랜드',
 '평판',
 '전기',
 '제품',
 '상장',
 '기업',
 '순위',
 '위',
 '에너지',
 '솔루션',
 '위',
 '삼성',
 '위',
 '에코',
 '프로비',
 '엠',
 '삼성',
 '그룹',
 '시가총액',
 '껑충',
 '삼성',
 '상승',
 '주목',
 '하이닉스',
 '공매도',
 '거래',
 '일',
 '연속',
 '증가',
 '영업',
 '손실',
 '업황',
 '회복',
 '대감',
 '가트너',
 '올해',
 '휴대폰',
 '등',
 '디바이스',
 '출하',
 '감소',
 '예상',
 '사설',
 '역대',
 '최대',
 '무역적자',
 '고난',
 '행군',
 '각오',
 '공매도',
 '거래',
 '일',
 '연속',
 '증가',
 '리보',
 '세라',
 '닙',
 '간암',
 '차',
 '치료',
 '제',
 '승인',
 '금',
 '그린',
 '파워',
 '코스닥',
 '상장',
 '추진',
 '메모리',
 '강국',
 '삼성',
 '하이닉스',
 '동반',
 '적자',
 '우려',
 '울산',
 '대기업',
 '온실가스',
 '배출',
 '량',
 '국가',
 '감축',
 '목표',
 '설정',
 '후',
 '되레',
 '검찰',
 '김성태',
 '대북',
 '송금',
 '관련',
 '이재명',
 '제',
 '자',
 '뇌물죄',
 '조준',
 '김진용',
 '인천',
 '경제',
 '청장',
 '긴밀',
 '협력',
 '지원',
 '통해',
 '첨단',
 '산업',
 '클러스터',
 '발전',
 '최선',
 '뉴딜',
 '에코',
 '프로비',
 '엠',
 '급등',
 '상승세',
 '셀트리온',
 '공매도',
 '건',
 '마시스',
 '상대',
 '진단',
 '키트',
 '계약',
 '위반',
 '손',
 '배소',
 '제기',
 '한국',
 '케다',
 '제약',
 '엑스',
 '키비',
 '티',
 '출시',
 '일상생활',
 '유지',
 '복용',
 '가능',
 '환자',
 '생존',
 '기간',
 '연장',
 '기대',
 '바이오',
 '뉴딜',
 '셀트리온',
 '헬',
 '스케',
 '상',
 '승률',
 '상위',
 '다산',
 '칼럼',
 '토종',
 '플랫폼',
 '글로벌',
 '기업',
 '반도체',
 '겨울',
 '무역적자',
 '역대',
 '최대',
 '병원',
 '이모저모',
 '고려대',
 '명',
 '순천향대',
 '천안',
 '삼성',
 '서울',
 '병원',
 '등',
 '소식',
 '최초',
 '엑손',
 '변',
 '폐암',
 '치료',
 '제',
 '엑스',
 '키비',
 '티',
 '출시',
 '부산',
 '평생교육',
 '국가',
 '공인',
 '산업',
 '보안관',
 '리사',
 '과정',
 '신설',
 '키',
 '의',
 '농구',
 '스타',
 '김영희',
 '거인병',
 '윤',
 '부근',
 '전',
 '삼성',
 '전자',
 '부회장',
 '고향',
 '울릉도',
 '원',
 '기부',
 '박지원',
 '김건희',
 '여사',
 '짜장면',
 '김연주',
 '김정숙',
 '단독',
 '이슈',
 '한국',
 '축구',
 '미래',
 '이강인',
 '규',
 '이적설',
 '결실',
 '캐터필러',
 '호실',
 '주가',
 '하락',
 '장기',
 '호황',
 '기',
 '속',
 '피크',
 '아웃',
 '우려',
 '보험',
 '업법',
 '개정',
 '논의',
 '재',
 '점화',
 '삼성',
 '생명',
 '고객',
 '돈',
 '지급',
 '언제',
 '부고',
 '임',
 '동준',
 '전',
 '동양제과',
 '부사',
 '씨',
 '별세',
 '삼성',
 '전자',
 '신규',
 '프리미엄',
 '노트북',
 '갤럭시',
 '북',
 '울트라',
 '공개',
 '억',
 '소리',
 '나',
 '카메라',
 '진화',
 '현재',
 '진행형',
 '삼성',
 '갤럭시',
 '르포',
 '미국',
 '속',
 '을지로',
 '밤',
 '거리',
 '를',
 '갤럭시',
 '울트라',
 '갤럭시',
 '팩',
 '카메라',
 '장점',
 '울트라',
 '게이',
 '밍폰',
 '등',
 '기본',
 '갤럭시',
 '팩',
 '그래픽',
 '카메라',
 '배터리',
 '삼성',
 '갤럭시',
 '북',
 '삼총사',
 '발표',
 '첫',
 '울트라',
 '노트북',
 '출시',
 '샌프란',
 '만난',
 '울트라',
 '밤',
 '거리',
 '선명',
 '삼성',
 '팩',
 '인텔',
 '세대',
 '프로세서',
 '갤럭시',
 '북',
 '시리즈',
 '삼성',
 '전자',
 '갤럭시',
 '성능',
 '역대',
 '최고',
 '카메라',
 '갤럭시',
 '팩',
 '스마트폰',
 '혁신',
 '친환경',
 '기술',
 '완성',
 '애플',
 '갤럭시',
 '북',
 '공개',
 '화소',
 '괴물',
 '칩',
 '베일',
 '최고',
 '중',
 '최고',
 '삼성',
 '승부',
 '수',
 '울트라',
 '개',
 '부품',
 '재활용',
 '소재',
 '전작',
 '배',
 '친환경',
 '기술',
 '혁신',
 '갤럭시',
 '개',
 '재활용',
 '소재',
 '부품',
 '적용',
 '삼성',
 '전자',
 '파트너',
 '개방',
 '협력',
 '재활용',
 '소재',
 '확대',
 '삼성',
 '전자',
 '갤럭시',
 '북',
 '시리즈',
 '의',
 '타깃',
 '게이머',
 '크리에이터',
 '카메라폰',
 '끝판',
 '갤럭시',
 '출시',
 '일반',
 '모델',
 '갤럭시',
 '팩',
 '울트라',
 '로',
 '온',
 '북',
 '프리미엄',
 '노트북',
 '시장',
 '정',
 '조준',
 '폰',
 '밤하늘',
 '성운',
 '은하',
 '카메라',
 '혁신',
 '뚜껑',
 '연',
 '시리즈',
 '화소',
 '카메라',
 '게임',
 '폰',
 '국내출시',
 '화소',
 '카메라',
 '손',
 '선명',
 '갤럭시',
 '최고',
 '성능',
 '갤럭시',
 '팩',
 '나',
 '캐논',
 '이재용',
 '화소',
 '폰',
 '카메라',
 '승부',
 '삼성',
 '팩',
 '진화',
 '본능',
 '화소',
 '눈',
 '첫',
 '선',
 '갤럭시',
 '팩',
 '이제',
 '노트북',
 '울트라',
 '삼성',
 '갤럭시',
 '북',
 '시리즈',
 '선봬',
 '최고',
 '성능',
 '갤럭시',
 '북',
 '갤럭시',
 '북',
 '울트라',
 '공개',
 '갤럭시',
 '팩',
 '내',
 '영화감독',
 '샌프란',
 '중심부',
 '디지털',
 '놀이터',
 '삼성',
 '갤럭시',
 '팩',
 '로',
 '게이',
 '밍',
 '성능',
 '개선',
 '삼성',
 '전자',
 '괴물',
 '카메라',
 '탑재',
 '갤럭시',
 '시리즈',
 '공개',
 '갤럭시',
 '퀄컴',
 '맞춤',
 '스냅드래곤',
 '탑재',
 '최강',
 '게임',
 '디바이스',
 '갤럭시',
 '팩',
 '애플',
 '맥북',
 '프로',
 '삼성',
 '북',
 '울트라',
 '로',
 '승부',
 '수',
 '영상',
 '갤럭시',
 '팩',
 '노',
 '태문',
 '자신감',
 '아이폰',
 '인기',
 '반도체',
 '우주',
 '등',
 '개',
 '기술',
 '인재',
 '양성',
 '대통령',
 '직접',
 '이재용',
 '회장',
 '대신',
 '로',
 '삼성',
 '밤낮',
 '카메라',
 '경험',
 '재활용',
 '부품',
 '삼성',
 '갤럭시',
 '팩',
 '카메라',
 '고도화',
 '로',
 '게이',
 '밍',
 '성능',
 '대폭',
 '개선',
 '갤럭시',
 '기본',
 '사진',
 '편집',
 '도구로',
 '어도비',
 '라이트룸',
 '탑재',
 '역대',
 '최강',
 '울트라',
 '전작',
 '점',
 '베일',
 '갤럭시',
 '갤럭시',
 '팩',
 '베일',
 '시리즈',
 '눈',
 '화소',
 '카메라',
 '과',
 '두뇌',
 '전용',
 '스마트폰',
 '몸',
 '교감',
 '하이엔드',
 '노트북',
 '끝판',
 '삼성',
 '전자',
 '신규',
 '고성능',
 '프리미엄',
 '노트북',
 '갤럭시',
 '북',
 '울트라',
 '공개',
 '카메라',
 '은하수',
 '속도',
 '애플',
 '삼성',
 '전자',
 '갤럭시',
 '종',
 '공개',
 '연결',
 '갤럭시',
 '북',
 '전화',
 '메시지',
 '확인',
 '가능',
 '베일',
 '갤럭시',
 '화소',
 '카메라',
 '최강',
 '로',
 '승부',
 '수',
 '카메라',
 '게이',
 '밍',
 '최강',
 '스펙',
 '프리미엄',
 '폰',
 '기준',
 '삼성',
 '갤럭시',
 '팩',
 '화소',
 '카메라',
 '강점',
 '장시간',
 '게임',
 '시',
 '발열',
 '우려',
 '오프라인',
 '갤럭시',
 '팩',
 '역대',
 '성능',
 '갤럭시',
 '베일',
 '갤럭시',
 '친환경',
 '소재',
 '확대',
 '적용',
 '더욱',
 '부고',
 '김철',
 '린',
 '별세',
 '삼성',
 '갤럭시',
 '팩',
 '갤럭시',
 '북',
 '울트라',
 '로',
 '생산',
 '갤럭시',
 '카메라',
 '성능',
 '올인',
 '화소',
 '눈',
 '두뇌',
 '사진',
 '최적화',
 '논란',
 '전량',
 '퀄컴',
 '칩',
 '갤럭시',
 '공개',
 '삼성',
 '갤럭시',
 '팩',
 '실적',
 '점유',
 '율',
 '반등',
 '포토',
 '갤럭시',
 '꿀떡',
 '에디',
 '션',
 '팬텀',
 '블랙',
 '그린',
 '라벤더',
 '크림',
 '중',
 '갤럭시',
 '팩',
 '지구',
 '생각',
 '갤럭시',
 '곳곳',
 '재활용',
 '소재',
 '확대',
 '갤럭시',
 '팩',
 '친환경',
 '기술',
 '혁신',
 '삼성',
 '갤럭시',
 '재활용',
 '소재',
 '확대',
 '사용',
 '갤럭시',
 '팩',
 '지원',
 '삼성',
 '전자',
 '울트라',
 '사용',
 '갤럭시',
 '북',
 '출시',
 '영상',
 '갤럭시',
 '팩',
 '장점',
 '보따리',
 '갤럭시',
 '갤럭시',
 '북',
 '도',
 '엄지',
 '척',
 '카메라',
 '게이',
 '밍',
 '성능',
 '굿',
 '갤럭시',
 '체험',
 '관',
 '외신',
 '호평',
 '갤럭시',
 '팩',
 '울트라',
 '갤럭시',
 '북',
 '삼성',
 '노트북',
 '중',
 '최고',
 '성능',
 '삼성',
 '전자',
 '갤럭시',
 '시리즈',
 '공개',
 '오늘',
 '경기',
 '프로농구',
 '갤럭시',
 '팩',
 '갤럭시',
 '친환경',
 '기술',
 '혁신',
 '단계',
 '도약',
 '갤럭시',
 '팩',
 '괴물',
 '성능',
 '갤럭시',
 '북',
 '울트라',
 '갤럭시',
 '생태계',
 '완성',
 '갤럭시',
 '북',
 '터치',
 '번',
 '폰',
 '문서',
 '노트북',
 '화면',
 '삼성',
 '갤럭시',
 '팩',
 '친',
 '황경',
 '지속',
 '가능',
 '혁신',
 '앞장',
 '갤럭시',
 '팩',
 '삼성',
 '전자',
 '갤럭시',
 '북',
 '울트라',
 '로',
 '고성능',
 '프리미엄',
 '노트북',
 '진수',
 '갤럭시',
 '팩',
 '노',
 '태문',
 '카메라',
 '게임',
 '성능',
 '아이폰',
 '대응',
 '친환경',
 '갤럭시',
 '더',
 '더',
 '팩',
 '스마트폰',
 '연결',
 '삼성',
 '전자',
 '갤럭시',
 '북',
 '공개',
 '삼성',
 '전자',
 '역대',
 '최고',
 '성능',
 '디스플레이',
 '갤럭시',
 '북',
 '시리즈',
 '출시',
 '갤럭시',
 '팩',
 '갤럭시',
 '가격',
 '인상',
 '책',
 '성능',
 '품질',
 '승부',
 '삼성',
 '전자',
 '갤럭시',
 '출고',
 '인상',
 '삼성',
 '전자',
 '프리미엄',
 '노트북',
 '진화',
 '갤럭시',
 '북',
 '시리즈',
 '공개',
 '프리미엄',
 '스마트폰',
 '기준',
 '재정',
 '삼성',
 '갤럭시',
 '삼성',
 '전자',
 '화소',
 '괴물',
 '카메라',
 '갤럭시',
 '전격',
 '공개',
 '삼성',
 '전자',
 '사용자',
 '요구',
 '충족',
 '갤럭시',
 '북',
 '출시',
 '판매',
 '작일',
 '프리미엄',
 '부품',
 '출생',
 '비밀',
 '버려진',
 '것',
 '환골탈태',
 '갤럭시',
 '팩',
 '화소',
 '혁신',
 '카메라',
 '게이',
 '밍',
 '힘',
 '준',
 '역대',
 '최강',
 '갤럭시',
 ...]

In [ ]:
# Counter 불러오기
from collections import Counter
c = Counter(word_list)

In [ ]:
# 어떤 단어가 가장 많이 나왔을까?
c.most_common()

[('삼성', 12802),
 ('전자', 5371),
 ('갤럭시', 3116),
 ('포토', 2345),
 ('반도체', 2264),
 ('위', 1855),
 ('코스피', 1598),
 ('기업', 1173),
 ('등', 1145),
 ('카드', 1129),
 ('증권', 1123),
 ('출시', 1111),
 ('투자', 1100),
 ('기술', 1078),
 ('사', 1044),
 ('시장', 1040),
 ('생명', 998),
 ('이재용', 965),
 ('한국', 946),
 ('애플', 893),
 ('감독', 887),
 ('페이', 879),
 ('선', 849),
 ('공개', 839),
 ('시리즈', 826),
 ('회장', 814),
 ('지원', 811),
 ('보험', 810),
 ('개최', 792),
 ('상승', 779),
 ('경기', 778),
 ('사업', 765),
 ('전', 746),
 ('명', 724),
 ('산업', 715),
 ('개발', 711),
 ('마감', 711),
 ('주', 710),
 ('화재', 709),
 ('국내', 700),
 ('최대', 692),
 ('바이오', 683),
 ('기관', 678),
 ('판매', 658),
 ('업계', 630),
 ('글로벌', 629),
 ('비', 626),
 ('실적', 625),
 ('서울', 606),
 ('하락', 606),
 ('현대', 605),
 ('사전', 604),
 ('리그', 603),
 ('올해', 599),
 ('확대', 587),
 ('물산', 585),
 ('배터리', 578),
 ('것', 575),
 ('금융', 574),
 ('제', 572),
 ('첫', 570),
 ('거래', 542),
 ('진행', 539),
 ('사진', 538),
 ('주가', 537),
 ('오늘', 534),
 ('건설', 521),
 ('종합', 517),
 ('챗', 516),
 ('더', 503),
 ('강화', 499),
 ('세계', 498),
 ('배', 487),
 ('엑스포', 483),
 ('서비스', 480),
 ('대표', 478),
 ('전략', 476),
 ('초', 473),
 ('증시', 470),
 ('개', 468),
 ('금리', 465),
 ('디스플레이', 465),
 ('부산', 464),
 ('경쟁', 464),
 ('로', 456),
 ('지난해', 447),
 ('유치', 439),
 ('협력', 434),
 ('현장', 430),
 ('네이버', 430),
 ('황', 429),
 ('선정', 425),
 ('중', 424),
 ('손', 421),
 ('솔루션', 419),
 ('돌파', 418),
 ('달', 417),
 ('시작', 416),
 ('속', 415),
 ('매수', 414),
 ('미래', 409),
 ('미국', 403),
 ('튀르키예', 403),
 ('고객', 401),
 ('최고', 401),
 ('인재', 387),
 ('수', 382),
 ('이유', 374),
 ('임', 373),
 ('중국', 373),
 ('울트라', 370),
 ('하이닉스', 364),
 ('증가', 361),
 ('경영', 360),
 ('장', 357),
 ('그룹', 354),
 ('사전예약', 351),
 ('역대', 350),
 ('목표', 350),
 ('팀', 350),
 ('주식', 347),
 ('증권사', 344),
 ('성과급', 343),
 ('외국인', 342),
 ('경제', 340),
 ('종목', 340),
 ('최', 339),
 ('생산', 336),
 ('연속', 332),
 ('성장', 332),
 ('총', 331),
 ('이벤트', 331),
 ('율', 329),
 ('혜택', 327),
 ('발표', 325),
 ('점', 325),
 ('혁신', 323),
 ('실시', 322),
 ('차', 320),
 ('이사', 319),
 ('롯데', 318),
 ('은행', 315),
 ('외인', 314),
 ('주목', 313),
 ('세', 312),
 ('곳', 308),
 ('리', 306),
 ('전망', 306),
 ('작년', 306),
 ('더벨', 305),
 ('스', 304),
 ('내', 303),
 ('채용', 302),
 ('해외', 301),
 ('네트워크', 300),
 ('강세', 299),
 ('방문', 299),
 ('뉴스', 293),
 ('위해', 292),
 ('영업', 292),
 ('오픈', 292),
 ('코스닥', 290),
 ('카메라', 290),
 ('친환경', 290),
 ('정답', 289),
 ('확보', 288),
 ('규모', 287),
 ('새', 286),
 ('센터', 286),
 ('퀴즈', 286),
 ('신규', 284),
 ('스마트', 284),
 ('유럽', 283),
 ('매출', 283),
 ('현대차', 278),
 ('할인', 277),
 ('육성', 276),
 ('디지털', 275),
 ('단독', 274),
 ('이상', 274),
 ('상장', 272),
 ('사장', 271),
 ('기대', 269),
 ('본격', 266),
 ('피해', 266),
 ('추진', 264),
 ('국제', 264),
 ('병원', 262),
 ('수원', 262),
 ('부고', 258),
 ('의', 258),
 ('북', 258),
 ('위기', 257),
 ('원', 257),
 ('시즌', 257),
 ('용', 257),
 ('연패', 257),
 ('한화', 256),
 ('팩', 255),
 ('프로', 255),
 ('운영', 255),
 ('이슈', 254),
 ('신한은행', 254),
 ('후', 253),
 ('개막', 253),
 ('연승', 252),
 ('테크', 252),
 ('개통', 252),
 ('관련', 251),
 ('이', 251),
 ('직원', 251),
 ('로봇', 248),
 ('스타트업', 247),
 ('법', 247),
 ('개선', 246),
 ('에코', 244),
 ('부회장', 244),
 ('재', 244),
 ('강', 244),
 ('인하', 242),
 ('회', 242),
 ('공장', 242),
 ('우리', 241),
 ('우려', 239),
 ('선수', 238),
 ('인력', 238),
 ('디자인', 236),
 ('자산운용', 236),
 ('익', 235),
 ('매도', 235),
 ('잔치', 235),
 ('신용', 234),
 ('정부', 233),
 ('개인', 231),
 ('공략', 231),
 ('점검', 231),
 ('주간', 230),
 ('스마트폰', 229),
 ('부동산', 229),
 ('수출', 228),
 ('도전', 228),
 ('자율', 228),
 ('급등', 226),
 ('폰', 226),
 ('안', 226),
 ('승리', 226),
 ('전기', 225),
 ('계', 225),
 ('결제', 225),
 ('기능', 224),
 ('대구', 224),
 ('체험', 223),
 ('수주', 223),
 ('대기업', 222),
 ('관심', 222),
 ('봄', 221),
 ('희망', 220),
 ('년', 219),
 ('시대', 219),
 ('출발', 218),
 ('펀드', 217),
 ('패션', 217),
 ('수상', 217),
 ('공식', 217),
 ('상', 216),
 ('일', 215),
 ('씨', 215),
 ('통신', 215),
 ('환율', 215),
 ('수요', 213),
 ('입', 212),
 ('나', 211),
 ('하나', 211),
 ('지역', 210),
 ('게임', 209),
 ('더블', 209),
 ('적용', 208),
 ('협회', 208),
 ('계약', 207),
 ('집중', 207),
 ('브랜드', 205),
 ('준비', 205),
 ('대상', 205),
 ('협약', 204),
 ('체결', 204),
 ('핵심', 204),
 ('재활용', 203),
 ('신임', 203),
 ('자', 202),
 ('우리은행', 201),
 ('프리미엄', 200),
 ('대통령', 200),
 ('캠프', 200),
 ('인터뷰', 199),
 ('가스', 199),
 ('특징', 199),
 ('회복', 197),
 ('모바일', 197),
 ('카카오', 197),
 ('규', 196),
 ('공급', 196),
 ('지진', 196),
 ('진출', 195),
 ('부문', 195),
 ('달성', 195),
 ('배당', 194),
 ('전환', 194),
 ('지능', 194),
 ('제약', 193),
 ('대외', 193),
 ('선봬', 192),
 ('노', 192),
 ('리츠', 192),
 ('위험', 191),
 ('가전', 190),
 ('선임', 190),
 ('공모', 190),
 ('교육', 190),
 ('신제품', 189),
 ('테슬라', 189),
 ('우승', 188),
 ('치료', 187),
 ('온', 187),
 ('관', 187),
 ('도', 186),
 ('지속', 186),
 ('왜', 186),
 ('아이', 186),
 ('최초', 185),
 ('특허', 185),
 ('통', 183),
 ('이익', 183),
 ('전시', 183),
 ('분석', 182),
 ('참가', 182),
 ('양성', 181),
 ('시스템', 181),
 ('후보', 181),
 ('첨단', 180),
 ('상위', 180),
 ('가장', 180),
 ('코리아', 180),
 ('광주', 180),
 ('내달', 180),
 ('공동', 179),
 ('노조', 179),
 ('페어', 178),
 ('프로모션', 178),
 ('금', 177),
 ('문제', 177),
 ('다음', 177),
 ('복귀', 177),
 ('홍보', 177),
 ('엔솔', 176),
 ('확정', 176),
 ('인사', 176),
 ('점유', 175),
 ('마켓', 175),
 ('대전', 175),
 ('건강', 173),
 ('향', 173),
 ('감소', 172),
 ('세대', 172),
 ('승부', 172),
 ('힘', 172),
 ('및', 172),
 ('보합', 172),
 ('모델', 171),
 ('다시', 171),
 ('차기', 171),
 ('열사', 170),
 ('출범', 170),
 ('아이폰', 169),
 ('가격', 169),
 ('포스코', 169),
 ('성공', 169),
 ('볼', 169),
 ('건', 168),
 ('논란', 167),
 ('주행', 167),
 ('전쟁', 167),
 ('티', 166),
 ('가능', 166),
 ('개국', 166),
 ('기록', 166),
 ('랩', 166),
 ('취임', 165),
 ('기회', 165),
 ('수익', 165),
 ('나노', 165),
 ('공매도', 164),
 ('추가', 164),
 ('공사', 164),
 ('노트북', 163),
 ('돈버', 163),
 ('홈', 162),
 ('그', 162),
 ('전남', 162),
 ('업데이트', 162),
 ('출신', 161),
 ('인상', 161),
 ('도입', 161),
 ('대비', 161),
 ('전시회', 161),
 ('돈', 160),
 ('판', 160),
 ('보상', 160),
 ('버스', 160),
 ('사주', 160),
 ('국가', 159),
 ('상반기', 159),
 ('기반', 159),
 ('메', 159),
 ('대감', 158),
 ('소식', 158),
 ('영상', 158),
 ('오키나와', 158),
 ('행사', 158),
 ('폭', 158),
 ('마케팅', 158),
 ('유통', 158),
 ('인기', 157),
 ('주요', 157),
 ('또', 157),
 ('플랫폼', 156),
 ('구글', 156),
 ('운용', 156),
 ('처', 156),
 ('바', 156),
 ('제품', 155),
 ('대출', 155),
 ('석', 155),
 ('못', 154),
 ('참여', 154),
 ('특화단', 154),
 ('직스', 153),
 ('업무', 153),
 ('눈', 152),
 ('손해', 152),
 ('단지', 152),
 ('아시아', 152),
 ('장관', 152),
 ('정', 151),
 ('연', 151),
 ('에너지', 150),
 ('효과', 150),
 ('당국', 150),
 ('대표이사', 150),
 ('공격', 150),
 ('호', 150),
 ('주년', 150),
 ('맞춤', 149),
 ('자산', 149),
 ('달러', 149),
 ('대표팀', 149),
 ('기', 148),
 ('강남', 148),
 ('성능', 147),
 ('속도', 147),
 ('때', 147),
 ('일본', 147),
 ('액', 147),
 ('분양', 147),
 ('선두', 146),
 ('구매', 146),
 ('소재', 145),
 ('메타', 144),
 ('라운드', 143),
 ('경기도', 143),
 ('이승기', 143),
 ('개시', 143),
 ('보험사', 142),
 ('이통', 142),
 ('자동차', 141),
 ('개미', 141),
 ('이자', 141),
 ('금감원', 141),
 ('태문', 140),
 ('생태계', 140),
 ('여자농구', 140),
 ('클럽', 140),
 ('이번', 140),
 ('약세', 140),
 ('천안', 139),
 ('대응', 139),
 ('긴축', 139),
 ('특별', 139),
 ('정기', 139),
 ('슛', 139),
 ('선물', 139),
 ('복구', 139),
 ('경험', 138),
 ('상품', 138),
 ('미래에셋', 138),
 ('탈출', 138),
 ('한종', 138),
 ('연결', 137),
 ('반등', 137),
 ('박', 137),
 ('논의', 136),
 ('활용', 136),
 ('가능성', 136),
 ('두', 136),
 ('협업', 136),
 ('셀', 136),
 ('채권', 136),
 ('비트코인', 135),
 ('과정', 135),
 ('성과', 135),
 ('폴', 135),
 ('예약', 134),
 ('차세대', 134),
 ('득점', 134),
 ('생', 133),
 ('데이터', 133),
 ('열풍', 133),
 ('상륙', 133),
 ('인천', 132),
 ('아웃', 132),
 ('감', 132),
 ('한정판', 132),
 ('기자', 132),
 ('기념', 132),
 ('내정', 132),
 ('제철', 132),
 ('차량', 131),
 ('리포트', 131),
 ('스포츠', 131),
 ('대신', 130),
 ('외', 130),
 ('디딤돌', 130),
 ('브리핑', 130),
 ('등기', 130),
 ('전문가', 130),
 ('데이', 130),
 ('법인', 130),
 ('주주', 129),
 ('정규', 129),
 ('화소', 128),
 ('사용', 128),
 ('사회', 128),
 ('돌입', 128),
 ('팝업', 128),
 ('도망', 128),
 ('사자', 127),
 ('독일', 127),
 ('소각', 127),
 ('준', 126),
 ('수준', 126),
 ('누구', 126),
 ('구축', 126),
 ('부진', 126),
 ('블루', 126),
 ('필터', 126),
 ('오', 125),
 ('개월', 125),
 ('치킨', 125),
 ('불', 124),
 ('제공', 124),
 ('부', 124),
 ('결과', 124),
 ('평가', 124),
 ('관리', 124),
 ('아트', 124),
 ('수비', 124),
 ('영', 124),
 ('데', 124),
 ('끝', 123),
 ('승', 123),
 ('융자', 123),
 ('아산', 123),
 ('탄소', 123),
 ('다이렉트', 123),
 ('스튜디오', 123),
 ('부품', 122),
 ('규제', 122),
 ('마련', 122),
 ('바이', 122),
 ('모집', 122),
 ('큐', 121),
 ('영향', 121),
 ('울산', 120),
 ('불황', 120),
 ('사상', 119),
 ('교수', 119),
 ('장비', 119),
 ('스포크', 119),
 ('사이드', 119),
 ('흥행', 118),
 ('은', 118),
 ('전기차', 118),
 ('교보', 118),
 ('대형', 117),
 ('의료', 117),
 ('온라인', 117),
 ('훈련', 116),
 ('치매', 116),
 ('번가', 116),
 ('인', 116),
 ('의사', 116),
 ('광고', 116),
 ('도약', 115),
 ('보사', 115),
 ('발', 115),
 ('가입', 115),
 ('전문', 115),
 ('플러스', 115),
 ('예측', 115),
 ('아난', 115),
 ('침체', 114),
 ('줄', 114),
 ('손보', 114),
 ('세탁기', 114),
 ('유지', 113),
 ('탑재', 113),
 ('호텔', 113),
 ('동맹', 113),
 ('아파트', 113),
 ('패키지', 113),
 ('업체', 113),
 ('기부', 112),
 ('퀄컴', 112),
 ('부담', 112),
 ('단', 112),
 ('팔자', 112),
 ('효율', 112),
 ('한도', 112),
 ('부총리', 112),
 ('시', 111),
 ('상생', 111),
 ('투', 111),
 ('예상', 110),
 ('그린', 110),
 ('중공업', 110),
 ('정책', 110),
 ('정상', 110),
 ('순이익', 110),
 ('공기', 110),
 ('훈풍', 109),
 ('청년', 109),
 ('회사', 109),
 ('검찰', 108),
 ('상승세', 108),
 ('과', 108),
 ('파운드리', 108),
 ('웨딩', 108),
 ('앱', 108),
 ('대금', 108),
 ('종', 107),
 ('필요', 107),
 ('리더십', 107),
 ('학기', 107),
 ('김소니아', 107),
 ('엠', 106),
 ('이마트', 106),
 ('료', 106),
 ('최태원', 106),
 ('모빌리티', 106),
 ('정화', 106),
 ('메모리', 105),
 ('이제', 105),
 ('일정', 105),
 ('유플러스', 105),
 ('신청', 105),
 ('전량', 104),
 ('앞', 104),
 ('보험료', 104),
 ('스토어', 104),
 ('포기', 104),
 ('은희', 104),
 ('기획전', 104),
 ('다인', 104),
 ('격차', 103),
 ('경쟁력', 103),
 ('조선', 103),
 ('쇼', 103),
 ('이자율', 103),
 ('모터', 103),
 ('압수수색', 103),
 ('리뷰', 102),
 ('추천', 102),
 ('체계', 102),
 ('래미안', 102),
 ('인공', 102),
 ('사고', 102),
 ('대한민국', 102),
 ('탁구', 102),
 ('시몬', 102),
 ('극복', 101),
 ('인증', 101),
 ('말', 101),
 ('론', 101),
 ('건설업', 101),
 ('보조금', 101),
 ('칩스', 101),
 ('제한', 101),
 ('디시', 101),
 ('듯', 100),
 ('모두', 100),
 ('암', 100),
 ('사이버', 100),
 ('하이브', 100),
 ('네오', 100),
 ('공조', 100),
 ('량', 99),
 ('신설', 99),
 ('축소', 99),
 ('스타벅스', 99),
 ('요청', 99),
 ('동반', 98),
 ('빅', 98),
 ('피', 98),
 ('트', 98),
 ('해', 98),
 ('사내', 98),
 ('중단', 97),
 ('한파', 97),
 ('연습', 97),
 ('민간', 97),
 ('급락', 97),
 ('구호', 97),
 ('배혜윤', 97),
 ('여성', 97),
 ('칼럼', 96),
 ('률', 96),
 ('안정', 96),
 ('평균', 96),
 ('민원', 96),
 ('잡고', 96),
 ('평판', 95),
 ('부사', 95),
 ('환경', 95),
 ('카', 95),
 ('캐롯', 95),
 ('고용', 95),
 ('오후', 95),
 ('이해', 95),
 ('리바운드', 95),
 ('모델링', 95),
 ('항공', 95),
 ('캠퍼스', 95),
 ('권영수', 95),
 ('현재', 94),
 ('프로농구', 94),
 ('확장', 94),
 ('꿈', 94),
 ('수익률', 94),
 ('부상', 94),
 ('원장', 94),
 ('의혹', 94),
 ('이정현', 94),
 ('국민', 94),
 ('이크', 94),
 ('건조기', 94),
 ('인도', 93),
 ('백화점', 93),
 ('시간', 93),
 ('도시', 93),
 ('인수', 93),
 ('매각', 93),
 ('선언', 93),
 ('미소', 93),
 ('전세계', 93),
 ('캠페인', 93),
 ('표준', 93),
 ('참석', 93),
 ('추격', 93),
 ('한국전력', 93),
 ('개막전', 93),
 ('발병', 93),
 ('디', 92),
 ('하나원', 92),
 ('워치', 92),
 ('한미', 92),
 ('연대', 92),
 ('란', 92),
 ('빅스', 92),
 ('적자', 91),
 ('스타', 91),
 ('칩', 91),
 ('국', 91),
 ('계획', 91),
 ('선택', 91),
 ('사외이사', 91),
 ('예정', 91),
 ('가치', 91),
 ('존', 91),
 ('지정', 91),
 ('개편', 91),
 ('선발', 91),
 ('침대', 91),
 ('공기청정기', 91),
 ('강조', 90),
 ('간다', 90),
 ('조선업', 90),
 ('린다', 90),
 ('활동', 90),
 ('식품', 90),
 ('교통카드', 90),
 ('파워', 89),
 ('주의', 89),
 ('현', 89),
 ('장사', 89),
 ('배드민턴', 89),
 ('공정', 89),
 ('심포지엄', 89),
 ('에이', 89),
 ('거대', 89),
 ('상대', 88),
 ('비즈', 88),
 ('어디', 88),
 ('나선', 88),
 ('빛', 88),
 ('소비자', 88),
 ('뒤', 88),
 ('홍대', 88),
 ('급증', 88),
 ('등록', 88),
 ('콘서트', 88),
 ('간편', 88),
 ('재계', 88),
 ('제임스', 88),
 ('농구', 87),
 ('눈길', 87),
 ('위원장', 87),
 ('등장', 87),
 ('박차', 87),
 ('팬', 87),
 ('에스', 87),
 ('분', 87),
 ('농협', 87),
 ('비리', 87),
 ('중동', 87),
 ('미디어', 87),
 ('순위', 86),
 ('별세', 86),
 ('포인트', 86),
 ('활성화', 86),
 ('방', 86),
 ('목소리', 86),
 ('이즈', 86),
 ('약품', 86),
 ('사람', 86),
 ('가구', 86),
 ('제재', 86),
 ('출격', 85),
 ('동향', 85),
 ('검토', 85),
 ('식물', 85),
 ('종료', 85),
 ('용인', 85),
 ('조정', 84),
 ('특화', 84),
 ('알뜰', 84),
 ('집', 83),
 ('결정', 83),
 ('케미칼', 83),
 ('언스', 83),
 ('스카이', 83),
 ('창립', 83),
 ('하루', 83),
 ('성수', 83),
 ('전경련', 83),
 ('컬렉션', 83),
 ('달인', 83),
 ('통해', 82),
 ('자신감', 82),
 ('확인', 82),
 ('션', 82),
 ('혼수', 82),
 ('역할', 82),
 ('셀틱', 82),
 ('간', 82),
 ('물가', 82),
 ('세미나', 82),
 ('맛집', 82),
 ('정신', 82),
 ('론칭', 82),
 ('간호사', 82),
 ('장기', 81),
 ('신고', 81),
 ('가지', 81),
 ('재고', 81),
 ('스페이스', 81),
 ('의원', 81),
 ('결혼', 81),
 ('평택', 81),
 ('김', 81),
 ('수혜', 81),
 ('리빙', 81),
 ('직접', 80),
 ('단계', 80),
 ('번', 80),
 ('역전', 80),
 ('신세계', 80),
 ('내일', 80),
 ('우리금융', 80),
 ('소통', 80),
 ('총력', 80),
 ('삼바', 80),
 ('예고', 80),
 ('가속', 80),
 ('제주', 80),
 ('안전', 80),
 ('클라우드', 80),
 ('위성', 80),
 ('프로비', 79),
 ('파트너', 79),
 ('문화', 79),
 ('채', 79),
 ('생활', 79),
 ('영화', 79),
 ('진입', 79),
 ('시도', 79),
 ('비상', 79),
 ('라이브', 79),
 ('총회', 79),
 ('공유', 79),
 ('분야', 79),
 ('신약', 79),
 ('특', 79),
 ('도심', 79),
 ('부스', 79),
 ('취업', 78),
 ('코치', 78),
 ('공시', 78),
 ('코로나', 78),
 ('자립', 78),
 ('이후', 78),
 ('특사', 78),
 ('베일', 77),
 ('날', 77),
 ('전자랜드', 77),
 ('계속', 77),
 ('물', 77),
 ('치', 77),
 ('하위', 77),
 ('지지', 77),
 ('사설', 76),
 ('승률', 76),
 ('톱', 76),
 ('압박', 76),
 ('층', 76),
 ('고덕', 76),
 ('선도', 76),
 ('창업', 76),
 ('텍', 76),
 ('국회', 76),
 ('층간소음', 76),
 ('환자', 75),
 ('업그레이드', 75),
 ('지금', 75),
 ('길', 75),
 ('프로그램', 75),
 ('우수', 75),
 ('임박', 75),
 ('출석', 75),
 ('액세서리', 75),
 ('대거', 75),
 ('림', 75),
 ('세상', 75),
 ('착', 75),
 ('부산물', 75),
 ('시동', 74),
 ('단체', 74),
 ('너', 74),
 ('초반', 74),
 ('빅데이터', 74),
 ('화학', 74),
 ('렐라', 74),
 ('에버랜드', 74),
 ('프라', 74),
 ('점슛', 73),
 ('해소', 73),
 ('행보', 73),
 ('유', 73),
 ('경북', 73),
 ('사도', 73),
 ('역량', 73),
 ('김시래', 73),
 ('완료', 73),
 ('강진', 73),
 ('이성민', 73),
 ('알', 72),
 ('업', 72),
 ('적극', 72),
 ('쿠팡', 72),
 ('하이퍼', 72),
 ('승격', 72),
 ('기업가', 71),
 ('기준', 71),
 ('만들기', 71),
 ('전국', 71),
 ('현지', 71),
 ('경계', 71),
 ('무', 71),
 ('철', 71),
 ('기존', 71),
 ('어워즈', 71),
 ('리스크', 71),
 ...]

In [ ]:
df

In [ ]:
# '삼성'이 들어간 제목만 필터링

# 신약, 주가 '주가' '증권' '배당' '순이익' '주식' '매수' '매도'
df = df[df['단어'].map(lambda x: '삼성' in x)].copy();df

df = df[df['단어'].map(lambda x: '주가' in x or '증권' in x or '배당' in x or '주식' in x or '매수' in x  or '매도' in x)].copy(); df

,제목,언론사,날짜,URL,네이버뉴스_URL,단어,제목_전처리
0,에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로비, 엠, 하이닉스, 삼성, 셀트리온, 현대, 로템, 외국인, 매수, ...",에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발 ...
1,"""사실상 감산""…삼성전자 띄우는 증권가",머니투데이,2023.02.02.,http://news.mt.co.kr/mtview.php?no=20230201230...,https://n.news.naver.com/mnews/article/008/000...,"[사실, 감산, 삼성, 전자, 증권]",사실상 감산 삼성전자 띄우는 증권가
2,"“삼성물산, 올해도 해외 프로젝트 기반 실적성장 기대”..매수 유지-이베스트",한국정경신문,2023.02.02.,http://kpenews.com/View.aspx?No=2701278,NaN,"[삼성, 물산, 올해, 해외, 프로젝트, 기반, 실적, 성장, 기대, 매수, 유지,...",삼성물산 올해도 해외 프로젝트 기반 실적성장 기대 매수 유지 이베스트
3,"[클릭 e종목]삼성물산, 지분가치에 연동된 주가 '목표주가 하향'",아시아경제,2023.02.02.,https://view.asiae.co.kr/article/2023020207593...,https://n.news.naver.com/mnews/article/277/000...,"[클릭, 종목, 삼성, 물산, 분, 가치, 연동, 주가, 목표, 주가, 하향]",클릭 e종목 삼성물산 지분가치에 연동된 주가 목표주가 하향
4,"삼성생명, 영업익 감소에도 배당 유지…오너가 짭짤",딜사이트,2023.02.02.,https://dealsite.co.kr/articles/98328,NaN,"[삼성, 생명, 영업, 익, 감소, 배당, 유지, 너, 짤]",삼성생명 영업익 감소에도 배당 유지 오너가 짭짤
...,...,...,...,...,...,...,...
841,"[데이터로 보는 증시] 삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일)",서울경제,2023.02.28.,https://www.sedaily.com/NewsView/29LXDJLTDM,https://n.news.naver.com/mnews/article/011/000...,"[데이터, 증시, 삼성, 전자, 현대차, 기관, 외국인, 코스피, 매수, 위]",데이터로 보는 증시 삼성전자 현대차 기관 외국인 코스피 순매수 1위 2월 28일
842,"삼성증권, 4분기 건전성 관리 빛났다…실적개선 기대감↑",녹색경제신문,2023.02.28.,http://www.greened.kr/news/articleView.html?id...,NaN,"[삼성, 증권, 건전성, 관리, 실적, 개선, 대감]",삼성증권 4분기 건전성 관리 빛났다 실적개선 기대감
843,[증시] 미국 주가 상승 영향으로 소폭 반등…기관 순매수 상위 종목은 삼성전자·LG...,톱스타뉴스,2023.02.28.,http://www.topstarnews.net/news/articleView.ht...,NaN,"[증시, 미국, 주가, 상승, 영향, 폭, 반등, 기관, 매수, 상위, 종목, 삼성...",증시 미국 주가 상승 영향으로 소폭 반등 기관 순매수 상위 종목은 삼성전자 LG...
844,"[더벨]삼성증권, 회사채 6200억 수요 모아...'KB·미래'의 절반",더벨,2023.02.28.,https://www.thebell.co.kr/free/content/Article...,NaN,"[더벨, 삼성, 증권, 회사채, 수요, 미래, 의, 절반]",더벨 삼성증권 회사채 6200억 수요 모아 KB 미래 의 절반
845,"[데이터로 보는 증시]삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일...",서울경제,2023.02.28.,https://www.sedaily.com/NewsView/29LXENGQ2M,https://n.news.naver.com/mnews/article/011/000...,"[데이터, 증시, 삼성, 전자, 현대차, 기관, 외국인, 코스피, 매수, 위, 최종...",데이터로 보는 증시 삼성전자 현대차 기관 외국인 코스피 순매수 1위 2월 28일...

In [ ]:
# 자연어 전처리: 텍스트 클리닝
import re
df['제목_전처리'] = df['제목'].map(lambda x: re.sub(r'[^\s\w]', ' ', x))

In [ ]:
df['제목_전처리']

0      에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발   ...
1                                   사실상 감산  삼성전자 띄우는 증권가
2              삼성물산  올해도 해외 프로젝트 기반 실적성장 기대   매수 유지 이베스트
3                    클릭 e종목 삼성물산  지분가치에 연동된 주가  목표주가 하향
4                            삼성생명  영업익 감소에도 배당 유지 오너가 짭짤
                             ...
841      데이터로 보는 증시  삼성전자 현대차  기관 외국인 코스피 순매수 1위 2월 28일
842                       삼성증권  4분기 건전성 관리 빛났다 실적개선 기대감
843     증시  미국 주가 상승 영향으로 소폭 반등 기관 순매수 상위 종목은 삼성전자 LG...
844               더벨 삼성증권  회사채 6200억 수요 모아    KB 미래 의 절반
845     데이터로 보는 증시 삼성전자 현대차  기관 외국인 코스피 순매수 1위 2월 28일...
Name: 제목_전처리, Length: 757, dtype: object

In [ ]:
# 인덱스 리셋
df.reset_index(drop=True, inplace=True)

In [ ]:
# TF-IDF 벡터화
vectorizer = TfidfVectorizer(min_df=10, ngram_range=(1,2), tokenizer = okt.morphs) #okt.nouns
features = vectorizer.fit_transform(df['제목_전처리'])

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [ ]:
# feature 이름 불러 오기
feature_names = vectorizer.get_feature_names_out()
feature_names

array(['1', '1 위', '2', '23일', '23일 부터', '2월', '3', '4월', '4월 초', '5',
       'fn', 'fn 리츠', 'gpt', 'kb', 'kb 증권', 'lg', 'lg 화학', 'sdi', 'sds',
       'sds 주식', 'sk', 'sk 하이닉스', 'ㆍ', 'ㆍ 에코', '家', '美', '美 주식', '證', '가',
       '강세', '개선', '개인', '거래', '거래 서비스', '거래 애프터', '거래 이벤트', '거래 활발',
       '고객', '고객 거래', '공모', '금리', '기', '기관', '기관 매도', '기관 순', '기관 외국인',
       '기업', '기업가', '기업가 치는', '납부', '네이버', '는', '대', '대상', '더벨', '데이터',
       '데이터 로', '도', '동향', '동향 외국인투자', '드', '드 자문', '등', '디지털', '디지털 부유',
       '랩', '랩 삼성', '로', '로 보는', '리츠', '리츠 증권', '리포트', '마감', '마켓',
       '마켓 거래', '매도', '매도 상위', '매도 에', '매매', '매매 동향', '매수', '매수 1',
       '매수 거래', '매수 상위', '매수 에', '목표', '목표 가', '목표 주가', '물산', '미국',
       '미국 주식', '미래에셋', '미래에셋 증권', '반도체', '발생', '발표', '배당', '보는', '보는 증시',
       '부고', '부고 조', '부유', '부유 층', '부터', '분석', '분석 리포트', '비상', '비상 장',
       '사업', '사주', '삼성', '삼성 fn', '삼성 sdi', '삼성 sds', '삼성 家', '삼성 물산',
       '삼성 생명', '삼성 전자', '삼성 증권', '삼성 화재', '상속세', '상속세 납부', '상승', '상위',
       '상위 종목', '상장', '상장 예정', '생명', '서', '서 제출', '서 효력', '서비스', '서비스 오픈',
       '선', '선물', '선물 거래', '성', '소', '소각', '소식', '솔루션', '수익', '순', '순 매도',
       '순 매수', '시장', '신', '신 인류', '신고', '신고 서', '신용', '신용 융자', '실적', '씨',
       '씨 장인상', '애프터', '애프터 마켓', '업계', '업계 도', '에', '에 2', '에코', '에코 프로비',
       '엠', '영', '영 삼성', '영업', '영향', '예', '예 드', '예정', '오픈', '올해', '외국인',
       '외국인 순', '외국인 코스피', '외국인투자', '외국인투자 자', '외인', '외인 매수', '위', '위 2월',
       '위 삼성', '유지', '유진', '유진 투자', '융자', '융자 이자율', '으로', '은', '은 삼성',
       '의', '이', '이벤트', '이벤트 진행', '이사', '이사 씨', '이사 장인상', '이서현', '이서현 삼성',
       '이자율', '이자율 인하', '인류', '인류 디지털', '인하', '자', '자 사주', '자문', '자문 형',
       '장', '장 삼성', '장 중', '장인상', '적', '전량', '전량 매도', '전망', '전자', '전자 sk',
       '전자 ㆍ', '전자 기관', '전자 주가', '전자 출시', '제', '제 영', '제공', '제출', '제출 4월',
       '조', '조 제', '종목', '종목 은', '주', '주 삼성', '주가', '주가 상승', '주가 하락',
       '주간', '주간 거래', '주식', '주식 전량', '주식 주간', '주주', '주체', '주체 매매', '중',
       '증권', '증권 美', '증권 가', '증권 기업', '증권 디지털', '증권 미국', '증권 삼성', '증권 신고',
       '증권 신용', '증권 업계', '증권 예', '증권 이사', '증권 투자', '증권 플러스', '증권 해외',
       '증권사', '증시', '증시 삼성', '증시 코스피', '지난해', '진행', '챗', '챗 gpt', '초',
       '초 상장', '최대', '최종', '최종 치', '추정', '추정 기업가', '출시', '층', '치', '치는',
       '카카오', '코스피', '코스피 기관', '코스피 순', '투', '투자', '투자 시장', '투자 주체',
       '투자 증권', '특징', '특징 주', '프로비', '프로비 엠', '플러스', '플러스 비상', '하락',
       '하이닉스', '하향', '한', '한 투', '한국', '한화', '해외', '해외 선물', '현대', '현대차',
       '형', '형 랩', '화재', '화학', '확대', '환원', '활발', '활발 추정', '회복', '효력',
       '효력 발생'], dtype=object)

In [ ]:
# DTM 생성
dtm_np = np.array(features.todense()); dtm_np

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.15201176, 0.16443992, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
# DataFrame 확인
pd.DataFrame(data = dtm_np, columns = feature_names)

,1,1 위,2,23일,23일 부터,2월,3,4월,4월 초,5,...,형 랩,화재,화학,확대,환원,활발,활발 추정,회복,효력,효력 발생
0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.16618,0.16618,0.0,0.0,0.0
1,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
2,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,0.166320,0.179918,0.0,0.0,0.0,0.210242,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
753,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
754,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.21328,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
755,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0
756,0.152012,0.164440,0.0,0.0,0.0,0.192154,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0

In [ ]:
# 코사인 유사도 구하기
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(dtm_np, dtm_np) #a 행렬과 b 행렬, 자기 자신과의 코사인 유사도 구하기 ...

In [ ]:
# 인덱스 설정
indices = pd.Series(df.index, index=df['제목']); indices

제목
에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발...추정 기업가치는?                     0
"사실상 감산"…삼성전자 띄우는 증권가                                                       1
“삼성물산, 올해도 해외 프로젝트 기반 실적성장 기대”..매수 유지-이베스트                                  2
[클릭 e종목]삼성물산, 지분가치에 연동된 주가 '목표주가 하향'                                        3
삼성생명, 영업익 감소에도 배당 유지…오너가 짭짤                                                 4
                                                                         ...
[데이터로 보는 증시] 삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일)                          752
삼성증권, 4분기 건전성 관리 빛났다…실적개선 기대감↑                                            753
[증시] 미국 주가 상승 영향으로 소폭 반등…기관 순매수 상위 종목은 삼성전자·LG에너지솔루션·SK하이닉스·LG화학·삼성SDI    754
[더벨]삼성증권, 회사채 6200억 수요 모아...'KB·미래'의 절반                                   755
[데이터로 보는 증시]삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일-최종치)                       756
Length: 757, dtype: int64

In [ ]:
# 뉴스 기사 제목 확인 하기
set(df['제목'])

{'"24시간 투자로 삼성에 맞불" NH·키움·토스, 미국주식 주간거래 참전',
 '"50억 중 40억이 빚, 사채도 썼다"…영끌 매수 아이파크삼성 결국 경매行',
 '"CJ CGV, 중국 박스오피스 사업 회복 전환 예상...목표가↑" -삼성증권',
 '"CJ ENM, 영업가치·보유지분 가치 상승...목표가↑"-삼성증권',
 '"DB손해보험, 우수 언더라이팅 효율성 부각될 듯" -삼성증권',
 '"F&F, 최악의 업황속에서 수익성 증명...영업이익률 28%" -삼성증권',
 '"HB테크놀러지, 삼성디스플레이 신규 수주 기정사실"-한양증권',
 '"KAI, 포트폴리오 정상화 지속"… 매수·목표주가 \'유지\'-삼성',
 '"SK바사, 現실적보단 미래를 봐야" 삼성증권 [Why 바이오]',
 '"SK아이이테크놀로지, 실적 기대치 하향 필요 " - 삼성증권',
 '"美 주식 최대 24시간 거래"…독점 끝난 삼성證에 도전장',
 '"격이 다른 프리미엄 투자케어"...삼성증권, 디지털부유층 서비스 강화',
 '"배당 수익률만 10%"…삼성전자 대신 주목받는 이 주식',
 '"부자 엄지족 잡아라"…삼성증권, 디지털자산관리 서비스 고도화',
 '"사실상 감산"…삼성전자 띄우는 증권가',
 '"삼성, 지배구조 개편 추진 안할 듯"...유안타증권',
 '"삼성SDI, 배터리 수익성 전략 주목"...신한투자증권',
 '"삼성물산, 친환경·바이오 등 신사업 투자 관련 성과 확인이 주가 상승 트리거"',
 '"삼성생명 양호한 손익 흐름, 주가 상승여력 26.5%"-신한투자',
 '"삼성생명, 경상이익 체력 증가 기대…투자의견 \'매수\' 유지"<교보證>',
 '"삼성생명, 배당확대와 자사주 소각 등 주주환원 가시성 높여야 한다"',
 '"삼성생명, 우리가 알던 매력은 변함없으나" - 현대차증권',
 '"삼성엔지니어링, 다양한 해외 프로젝트 주목"...하나증권',
 '"삼성전자 1분기 1조원대 영업이익 낼 것" 증권가 전망',
 '"삼성전자 주가 언제 반등할까요?"…전문가 \'깜짝 조언\' [차은지의 리치리치]',
 '"삼성전자 투자의견 \'매수\'…챗GPT 메모리 수요 긍정적 요인"',
 '"삼성전자, 2분기 실적 저점…주가 하락 위험 제한적"-KB',
 '"삼성전자, 반도체 공급조절 수혜 여부 주목"...대신증권',
 '"삼성전자, 하반기 반도체 수급 개선…목표주가 8만 원"',
 '"삼성증권 4분기 순영업수익 부진에 어닝쇼크…올해는 예상 부합할 것"-유안타',
 '"삼성증권, 순영업수익 부진으로 어닝쇼크"',
 '"삼성증권, 올해 이익 개선될 것…예상 배당수익률 6.2%"<이베스트투자證>',
 '"삼성증권, 지난해 4분기는 전부문 순영업이익 부진으로 어닝쇼크 기록"',
 '"삼성증권, 지난해 업황부진 심화가 실적악화로 반영"',
 '"삼성카드, 4분기 어닝서프라이즈" -하나증권',
 '"삼성카드, 배당성향과 DPS를 동시에 고려하는 정책으로 배당 가시성 높음"',
 '"서학개미 이동 환영" 美 주식 주간 거래 독점 삼성證에 경쟁사들 도전장',
 '"원익IPS, 급상승한 주가, 고정비 부담…목표가·투자의견↓"-삼성',
 '"챗GPT, 삼성전자 언제 사면 돼?"…챗GPT가 말하는 주식 시장',
 "'6만 전자' 회복한 삼성전자 주가 보합세, 증권가 전망 발표",
 "'AA급에 삼성인데'…삼성증권, 수요예측서 아쉬운 성적",
 "'대치타워·에스원빌딩' 보유…삼성FN리츠, 증권신고서 제출",
 "'삼성家의 상속세'…홍라희·이부진·이서현의 주식 활용법",
 "'삼성전자·네이버페이 협력' 이슈에 지니틱스 주가 급등",
 "'새 술은 새 부대에' 삼성증권 IPO본부장 교체···IB부문 조직안정화는 '진행형'",
 "'이자 장사' 비판 의식?...삼성·한투증권, 신용융자 이자율 인하",
 '(2보) 삼성물산, 전자 등 배당수익 최대 70% 환원',
 '10년 만에 배당 기대…삼성엔지니어링, 최대 실적에 주주환원',
 "23억 사채까지 써 '영끌' 매수한 아이파크 삼성… 결국 경매로",
 "50억 중 40억이 빚...'영끌 매수' 아이파크삼성 경매 매물로",
 '<부고> 조제영(삼성증권 이사)씨 장인상',
 '<부고> 조제영<삼성증권 이사>씨 장인상',
 '<부고> 조제영씨(삼성증권 이사) 빙부상',
 '<증권리포트 분석-2022년7월> ③삼성증권 9종목 애널리스트 1위',
 "CJ CGV, 中 박스오피스 회복에도 투자의견 '중립' - 삼성증권",
 'GKL, 높아진 용산 사업장 기대감...목표가↑-삼성증권',
 'HB인베-삼성증권, 370억원 규모 HB디지털혁신성장2호 펀드 결성',
 "HB인베스트-삼성증권, '디지털혁신성장' 두 번째 맞손",
 'KB증권 "삼성전자, 2분기 실적저점…하반기부터 회복세 진입"',
 'KB증권 "삼성전자, 컨센서스 하향 일단락…2분기 메모리 가격 바닥 근접"',
 'KB증권 “삼성전자 하반기 메모리 수급 개선, 20조 차입은 불가피”',
 'KB증권도 내렸다…한국투자·삼성증권 등 증권사 신용융자 이자율 인하 확산',
 '[#증권톡톡] 삼성증권 해외선물 거래·KB증권 해외 상장 ETF·ETN·한국투자증권 AIR ETF',
 '[2023 증권사 생존법] ④수익다각화 선전 삼성증권, 이유 있는 주가 강세',
 '[CEO뷰] 삼성증권 장석훈, 최악의 경영환경에서 진면목 보여줄까',
 "[ET라씨로] 삼성물산, '3조원 규모 자사주 전량 5년내 분할 소각' 소식에 주가 오름세",
 '[IT이슈] 증권플러스 비상장, 삼성증권 기업 분석 리포트 서비스 제공 外',
 "[POST-IPO] 삼성전자 27년 지기 '반도체 유통파트너' 미래반도체 ... 공모가 위로 주가 '훨훨'",
 '[SR경제&라이프] 삼성증권, 23일부터 신용융자 이자율 인하',
 '[fn마켓워치] 삼성증권, YTN 매각 주관사 철회키로',
 '[게시판] 삼성증권, 디지털 부유층 상대 서비스 확대',
 '[게시판] 삼성증권, 해외지수 선물 거래 서비스 개시',
 '[골든크로스 종목] 핀텔·이오플로우·라온테크 주가 상승…SK증권우·삼성엔지니어링·모델솔루션 주가 하락',
 '[공매도 TOP 10 종목] 코스피, 카카오뱅크 공매도 1위…미래에셋증권-카카오-삼성전자 등 순위 올라',
 '[관심주] 삼성생명, 명확한 배당정책 천명에 목표주가 유지',
 '[그래픽] 삼성 오너 일가 주식담보대출 규모 현황',
 '[급등주] 삼성공조, 주가 20%대 급등세',
 "[나인원의 내일장 홀인원] 삼성이 인정한 '디자인社' 파트너 삼성 믿고 주가 상승할 <가온칩스>",
 '[더벨][2023 Korea Wealth Management Awards]부동의 1위 삼성증권 PBS, 헤지펀드 만족도 최상위',
 "[더벨][이사회 모니터]삼성증권, 사내이사 2인 체제 고수 '임종룡 나비효과'",
 "[더벨][주주환원 비교 모니터]성장에 '올인'한 LG엔솔, 배당정책 앞선 삼성SDI",
 "[더벨][증권사 IB, 유상증자 전략]한국증권, HMM·삼성중공업 '극적반전' 조력자",
 "[더벨][증권사 커버리지 지도]SK그룹-SK증권, 변치않는 우정…삼성증권 '끼워볼까'",
 "[더벨][증권사 커버리지 지도]삼성증권, 롯데 '절친' KB증권 밀어냈다",
 "[더벨]삼성증권 새해 첫 IPO 금양그린파워 기관 관심 '최다'",
 "[더벨]삼성증권 연초 헤지펀드 '판매 드라이브'",
 "[더벨]삼성증권, '펀드 수탁 신사업' 연내 출격 채비",
 "[더벨]삼성증권, 대형 스팩 '두곳' 동시에 합병 대상 물색",
 "[더벨]삼성증권, 회사채 6200억 수요 모아...'KB·미래'의 절반",
 '[데이터로 보는 증시] LG전자 ·삼성전자, 기관·외국인 코스피 순매수 1위(2월 10일-최종치)',
 '[데이터로 보는 증시] NAVER·삼성전자, 기관·외국인 코스피 순매수 1위(2월 3일-최종치)',
 '[데이터로 보는 증시] POSCO홀딩스· 삼성전자, 기관·외국인 코스피 순매수 1위(2월 15일)',
 '[데이터로 보는 증시] 삼성전자, 기관·외국인 코스피 순매수 1위(2월 16일)',
 '[데이터로 보는 증시] 삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일)',
 '[데이터로 보는 증시] 카카오·삼성전자, 기관·외국인 코스피 순매수 1위(2월 9일)',
 '[데이터로 보는 증시]LG전자 ·삼성전자, 기관·외국인 코스피 순매수 1위(2월 10일)',
 '[데이터로 보는 증시]LG전자·삼성SDI, 기관·외국인 코스피 순매수 1위(2월 6일)',
 '[데이터로 보는 증시]LG전자·삼성SDI, 기관·외국인 코스피 순매수 1위(2월 6일-최종치)',
 '[데이터로 보는 증시]LG전자·삼성전자, 기관·외국인 코스피 주간 순매수 1위(2월 6일~2월 10일)',
 '[데이터로 보는 증시]LG화학 ·삼성전자, 기관·외국인 코스피 주간 순매수 1위 (2월 13일~17일)',
 '[데이터로 보는 증시]NAVER ·삼성전자, 기관·외국인 코스피 순매수 1위(2월 8일)',
 '[데이터로 보는 증시]NAVER·삼성전자, 기관·외국인 코스피 순매수 1위(2월 3일)',
 '[데이터로 보는 증시]NAVER·삼성전자, 기관·외국인 코스피 순매수 1위(2월 8일-최종치)',
 '[데이터로 보는 증시]NAVER·삼성전자, 기관·외국인 코스피 주간 순매수 1위(1월 30일~2월 3일)',
 '[데이터로 보는 증시]POSCO홀딩스·삼성전자, 기관·외국인 코스피 순매수 1위(2월 15일-최종치)',
 '[데이터로 보는 증시]POSCO홀딩스·삼성전자, 기관·외국인 코스피 순매수 1위(2월 17일)',
 '[데이터로 보는 증시]POSCO홀딩스·삼성전자, 기관·외국인 코스피 순매수 1위(2월 17일-최종치)',
 '[데이터로 보는 증시]삼성전자, 기관·외국인 코스피 순매수 1위(2월 16일-최종치)',
 '[데이터로 보는 증시]삼성전자·SK하이닉스, 기관·외국인 코스피 순매수 1위(2월 23일)',
 '[데이터로 보는 증시]삼성전자·SK하이닉스, 기관·외국인 코스피 순매수 1위(2월 23일-최종치)',
 '[데이터로 보는 증시]삼성전자·삼성SDI, 기관·외국인 코스피 순매수 1위(2월 14일)',
 '[데이터로 보는 증시]삼성전자·삼성SDI, 기관·외국인 코스피 순매수 1위(2월 14일-최종치)',
 '[데이터로 보는 증시]삼성전자·카카오페이, 기관·외국인 코스피 순매수 1위(2월 20일)',
 '[데이터로 보는 증시]삼성전자·카카오페이, 기관·외국인 코스피 순매수 1위(2월 20일-최종치)',
 '[데이터로 보는 증시]삼성전자·현대차, 기관·외국인 코스피 순매수 1위(2월 28일-최종치)',
 '[데이터로 보는 증시]삼성중공업·삼성전자, 기관·외국인 코스피 순매수 1위(2월 13일)',
 '[데이터로 보는 증시]삼성중공업·삼성전자, 기관·외국인 코스피 순매수 1위(2월 13일-최종치)',
 '[데이터로 보는 증시]카카오·삼성전자, 기관·외국인 코스피 순매수 1위(2월 9일-최종치)',
 '[동영상] 삼성엔지니어링, 외국인 10거래일째 순매수',
 '[마켓ING]삼성·하이닉스 2%대 상승 마감…금리 조절에 증권주도 강세',
 '[마켓인]삼성FN리츠 증권신고서 제출…4월 초 상장',
 '[부고] 삼성증권 조제영 이사 장인상',
 '[부고] 조제영 삼성증권 이사 장인상',
 '[부고] 조제영(삼성증권 이사 )씨 장인상',
 '[부고] 조제영(삼성증권 이사)씨 빙부상',
 '[부고] 조제영(삼성증권 이사)씨 장인상',
 '[부고] 조제영씨(삼성증권 이사) 장인상',
 '[부고]조제영(삼성증권 이사)씨 장인상',
 '[부고종합] 조제영 삼성증권 이사 장인상 등',
 '[부음] 조제영 삼성증권 이사 장인상',
 '[부음] 조제영(삼성증권 이사)씨 장인상',
 '[브랜드평판] 증권사 2023년 2월 빅데이터 분석결과... 1위 미래에셋증권, 2위 키움증권, 3위 삼성증권',
 '[빅데이터투데이] 증권사 2023년 2월 브랜드평판 랭킹.... 1위 미래에셋증권, 2위 키움증권, 3위 삼성증권',
 '[삼성그룹 월간동향] 삼성SDI 최근 한달간 주가 급등...계열사 중 상승률 선두',
 '[삼성증권 IB 새바람] 이재현 부사장, 골드만 노하우 살린다',
 "[삼성페이 관련주] 이루온·에이텍티앤·KG모빌리언스 주가 '활짝'... 기술력 지수는?",
 '[시그널] HB인베, 삼성증권 손잡고 최대 500억 벤처펀드 결성',
 "[신상품] 유진투자증권 '예드자문형 랩 삼성전자'",
 '[아시아에이TV] 미래에셋증권, 지난해 고객 경영 앞서...KB·삼성 순',
 '[애널픽] 삼성물산 주주라면 배당 말고 ‘이것’ 꼭 살펴',
 '[여의도 주식왕] HLB vs 삼성머스트스팩5호, 공략법은?',
 '[오늘의 증시] 코스피, 외인·기관 매도에 하락…삼성전자 3.45%↓',
 '[월간 투자주체 매매동향] 외국인투자자, 2월 삼성전자 1조1800억 순매수',
 "[이벤트] 삼성증권 '미국주식 거래시 기프티콘 제공'",
 "[이슈] '삼성증권' 독점 깨진 미국주식 주간거래…판도 변화 '주목'",
 '[종합주가지수] 1월 CPI 발표 직전 코스피 ‘UP‘…SK하이닉스·삼성SDI 등 주가↑',
 '[종합주가지수] FOMC 발표에 코스피도 ‘엄지 척’…삼성전자·카카오 등 주가↑',
 '[종합주가지수] 금리 헛물이었나…코스피 1.7% 후퇴, 삼성전자·SK하이닉스 등 주가↓',
 '[종합주가지수] 코스피도 물가·금리 ‘화들짝’…삼성SDI·LG화학 등 주가↓',
 '[주가 동향] 삼성화재, 주주환원 기대감에 목표가 27만7000원 유지',
 '[주식 분석] 삼성엔지니어링, 수주 파이프라인 확보... 목표주가 4만원',
 "[주식 초고수는 지금] 삼성전자 '로봇 인재' 육성 소식에 레인보우로보틱스 매수 1위",
 '[주식감별사] 포스코케미칼, 삼성SDI와 운명적 만남?',
 '[주식마감기사] 삼성페이·네이버페이 동맹에 지니틱스 상한가...디스플레이텍·비보존 제약 급등',
 '[증권가] 한국투자 NH투자 삼성증권 교보증권 현대차증권',
 '[증권상품 풍향계] 금융공학 모델로 삼성전자 투자하는 랩 출시',
 '[증권소식] "삼성전자, 지난해 임직원 보수 격차 32배"/가상인간이 주식투자정보 알려준다 등',
 "[증권소식] 1월 상장사 시총 189조 증가…삼성전자 33조 늘어/모태펀드 출자사업 경쟁률 7.5대 1/메리츠증권, 지난해 '1조 클럽' 달성 등",
 '[증권소식] 금투협 "증권사 일반환전 허용 환영"/삼성FN리츠 증권신고서 제출/금융권 부동산 PF 연체잔액 1조 돌파 등',
 '[증권소식] 지난해 IPO 공모액 전년 대비 21% 감소/차파트너스, 남양유업에 주주제안/삼성FN리츠, 공모 돌입…4월 상장 예정 등',
 "[증권소식] 한투 이어 삼성증권, 신용융자 이자율 인하/IBK증권 신임 대표에 서정학/NH투자증권, '나무 롯데카드' 출시 등",
 '[증시] 미국 FOMC 안도감에 코스피 0.8% 상승 마감…외인 순매수 상위 종목은 삼성전자·SK하이닉스·LG에너지솔루션·아모레퍼시픽·카카오',
 "[증시] 미국 긴축우려에 코스피 '출렁'…기관 순매도 상위 종목은 삼성전자·SK하이닉스·네이버·SK이노베이션·셀트리온",
 '[증시] 미국 주가 상승 영향으로 소폭 반등…기관 순매수 상위 종목은 삼성전자·LG에너지솔루션·SK하이닉스·LG화학·삼성SDI',
 '[증시] 미국발 긴축 우려에 코스피 1.7% 하락…기관 순매도 상위 종목은 삼성전자·SK하이닉스·셀트리온·한화솔루션·네이버',
 '[증시] 외인 매수에 코스피, 0.5% 올라 2,480선 탈환…외인 순매수 상위 종목은 삼성전자·현대차·LG에너지솔루션·SK하이닉스·기아',
 '[증시] 코스피, 0.55% 올라 2,450선 턱걸이…기관 순매도 상위 종목은 삼성전자·S-Oil·SK하이닉스·현대건설기계·현대미포조선',
 '[증시] 코스피, 1% 내려 2,450대 턱걸이 마감…기관 순매도 상위 종목은 삼성전자·삼성SDI·SK하이닉스·하이브·포스코케미칼',
 '[증시] 코스피, 2% 가까이 상승 마감…기관 순매수 상위 종목은 삼성전자·LG화학·SK하이닉스·현대차·네이버',
 '[증시] 코스피, 2,450대 강보합 마감…기관 순매도 상위 종목은 삼성전자·카카오·삼성SDI·셀트리온·SK하이닉스',
 '[증시] 코스피, 2,450대 약보합 마감…기관 순매도 상위 종목은 삼성전자·카카오·삼성SDI·LG에너지솔루션·하이브',
 '[증시] 코스피, 2,480대 약보합 마감…기관 순매도 상위 종목은 삼성전자·엔씨소프트·KB금융·신한지주·삼성SDI',
 '[증시] 코스피, 개인·기관 매수에 소폭 상승…외인 순매도 상위 종목은 LG화학·한화솔루션·포스코홀딩스·삼성전자·LG에너지솔루션',
 '[증시] 코스피, 기관 대량 매도에 2,460대로 하락…기관 순매도 상위 종목은 삼성전자·카카오·하이브·SK하이닉스·삼성SDI',
 '[증시] 코스피, 기관 순매수로 강보합세…기관 순매수 상위 종목은 삼성전자·SK하이닉스·LG전자·현대모비스·LG화학',
 '[증시] 코스피, 외국인 매수세에 2,480대로 상승…외인 순매수 상위 종목은 삼성전자·SK하이닉스·삼성SDI·삼성전자우·LG전자',
 '[증시] 코스피, 외인·기관 매도에 1.70% 급락…기관 순매도 상위 종목은 삼성전자·현대로템·삼성SDI·SK하이닉스·카카오',
 '[증시] 코스피, 외인·기관 쌍끌이 매도 속 1.5% 하락…기관 순매도 상위 종목은 삼성전자·SK이노베이션·한화솔루션·네이버·셀트리온',
 '[지구촌 한줄뉴스](종합) 미 반도체 엔비디아 주가·챗GPT·영국 채소 공급난·브렉시트·대만 미군 확대·삼성·SK 중국 반도체·우크라 평화 결의안·우크라이나 지원·세계은행 총재·차세대 전투기 우크라이나 지원·트란스니',
 '[채권을 사자] 삼성증권 "5%대 우량기업 회사채 보인다면…일단 담아라"',
 '[추천e종목] 갤럭시 S23 언팩…삼성전자 주가 오를까?',
 '[카드] 삼성증권, 미국주식 주간거래·애프터마켓 이벤트 실시',
 '[코스피 주간동향] 개인 순매수 TOP5는? POSCO홀딩스, 삼성전자, 한화솔루션, LG에너지솔루션, NAVER',
 '[코스피 주간동향] 외국인 순매수 상위 종목…삼성전자·현대차·기아',
 '[코스피] 외국인 순매수 TOP5 삼성전자·SK하이닉스·삼성SDI·KB금융·한화에어로스페이스',
 "[클릭 e종목]삼성물산, 지분가치에 연동된 주가 '목표주가 하향'",
 '[투자 주의 종목] 에이디칩스·삼성스팩6호 주가 상승…SM C&C·대모 주가 하락',
 '[투자주체 매매동향] 외국인 순매수 상위종목은?...삼성전자·현대차 순매수 상위권',
 '[투자주체 매매동향] 외국인, 삼성전자 1100억·SK하이닉스 420억 순매수',
 '[투자주체 매매동향] 외국인투자자, 삼성SDI 순매수 1위',
 '[투자주체 매매동향] 외국인투자자, 삼성SDI 집중 매수',
 '[투자주체 매매동향] 외국인투자자, 삼성전자 1020억 사들이며 순매수 1위',
 '[투자주체 매매동향] 외국인투자자, 삼성전자 1880억원 사들이며 순매수 1위',
 '[투자주체 매매동향] 외국인투자자, 삼성전자 508억 사들여 순매수 상위권',
 '[투자주체 매매동향] 외국인투자자, 삼성전자 977억 사들이며 순매수 1위',
 '[투자주체 매매동향] 외국인투자자, 삼성전자·한화솔루션·이마트 순매수 상위권',
 '[투자주체 매매동향] 외국인투자자, 한주간 삼성전자 2580억 사들이며 순매수 1위',
 '[투자주체 월간 매매동향] 외국인투자자, 2월 삼성전자·SK하이닉스 순매수 상위권',
 '[특징주] "3조원어치 자사주 전량 소각"…삼성물산, 장중 주가 6%대↑',
 '[특징주] 삼성SDI, 명확한 수익성 전략에도 주가 약세',
 '[특징주] 삼성물산 주가 하락···국내 자생식물 보존 앞장',
 '[특징주] 삼성물산 주가 하락···빈폴키즈, 세련된 스타일링 제안',
 '[특징주] 삼성물산 주가 하락···플랜씨, 골프 캡슐컬렉션 선보여',
 '[특징주] 삼성물산, 안정적 실적과 주주가치 제고에도 주가 약세',
 '[특징주] 삼성전자, 실적발표 이전 주가 6만3300원 수준으로 회복',
 '[특징주] 삼성증권, 작년 4분기 어닝쇼크에 주가 약세',
 '[특징주] 삼성카드, 4분기 서프라이즈 실적에도 주가 미지근',
 '[특징주] 삼성화재, 작년 순익 증가에도 주가 제자리',
 '[특징주] 삼진, 주가 상승세···삼성전자·챗GPT 협업 기대감',
 '[특징주] 신화콘텍, 삼성전자 XR 제품 개발 소식에 주가↑',
 '[특징주] 엔피, 주가 상한가...삼성전자 XR 생태계 확장 발표',
 '[특징주] 자사주 전량 소각·배당정책 유지 결정한 삼성물산, 6%대 강세',
 '[특징주] 지니틱스, 주가 20%대 상승세···삼성페이·네이버페이 협력 이슈 영향',
 '[프라임 인사이트] 최악의 실적 삼성전자 "주가는 외국인 손에 달려있어"',
 '[하이&로우] "디오, 체질 개선의 마무리 단계…목표가는 하향조정"-삼성증권',
 '[하이&로우] "휴젤, 2분기부터 中 리오프닝 수혜 기대"-삼성증권',
 '\u200b[투자주체 매매동향] 외국인투자자, 삼성전자 1420억 순매수하며 순매수 1위',
 '‘깜깜이 배당 개선안’ 당장 도입 요원…삼성전자, 주총 안건서 제외',
 '‘실적바닥=추세전환’?…삼성전자 매수권고 이어지는 이유 [투자360]',
 '‘이자 장사’ 손보는 증권가… 한투·삼성 ·KB 가세, 미래에셋·NH는?',
 '‘코스피 연초 랠리’ 외국인 6.5조 순매수…가장 많이 사들인 종목은 삼성전자',
 '“밤샘투자 그만”‥삼성증권, 미국주식 주간거래‧애프터마켓 ‘이벤트’',
 '“배당액 확인 뒤 투자하세요”…현대차·삼성증권 등 배당제도 개선 나서',
 '“삼성물산, 배당보다 신사업 투자 성과 주목…목표가 하향”',
 '“삼성물산, 올해도 해외 프로젝트 기반 실적성장 기대”..매수 유지-이베스트',
 '“삼성전자 주식, 개인이 왜 사요?” 24년차 IT애널의 투자 조언[딥다이브]',
 '“삼성전자, 호재 민감한 시기 진입…주가수익비율 빠른 상승”',
 '“삼성증권, 작년 4분기 실적 예상치 하회…올해 예상치 부합할 것”',
 '“삼성화재, 실적개선 지속 전망…배당주로 매력적”',
 '“삼성화재, 이익안전성 지속 전망…배당수익률 7% 달할 것”',
 '“상속세 납부”…삼성家 둘째 딸 이서현, 삼성SDS 주식 전량 매도',
 '“상속세 덜덜”…삼성家 이서현, 삼성SDS 주식 전량 매도',
 '“올해 8만전자 갈까”...증권가에 삼성전자 ‘핑크빛 전망’ 솔솔',
 '“주가 지지부진하네, 팔자”...23만 동학개미 삼성전자 떠났다',
 '“챗GPT야, 삼성전자 주가 계속 오르니?”…어닝쇼크가 ‘위기’ 아니란 3가지 이유 [센놈이 왔다-챗GPT]',
 "外人 폭풍매수, 코스피 '활짝'...삼성전자 · SK하이닉스 · LG전자 · 삼성SDI '급등'",
 '가교부터 투자까지... 유망 스타트업과 상생하는 삼성증권 [ESG클린리더스]',
 '가온칩스, 삼성 파운드리 이용 팹리스의 87% 고객사-현대차증권',
 '강원랜드, 사라진 방문객... 예상보다 더딘 회복 속도에 목표주가↓-삼성',
 '개인 배당액 1위는 이재용 삼성 회장…총 1991억 받는다',
 '경기침체에 50대 대기업 배당액 14%↓···삼성전자 이재용·현대차 정의선 회장은 배당 ‘1000억 클럽’',
 '경기침체에 주요 대기업 배당 14% 감소...배당액 1위는 삼성전자',
 '공모펀드 침체 속 증권사별 희비…신한·SK證 ‘약진’, 삼성·한투證 ‘후퇴’',
 '과대낙폭 반발매수 다우ㆍ나스닥 훨훨...테슬라도 상승 삼성SDIㆍ에코프로비엠 등 훈풍?',
 '교보證"삼성화재, 안정적 배당주로 매력적"',
 '교보증권 “삼성화재, 안정적인 배당주… 배당수익률 6.7%”',
 '교보증권·메리츠증권 “미국 주식, 앞으로 낮에 거래 가능… 삼성증권 독점 끝”',
 '국내 주요 대기업 실적 둔화에 배당 줄여, 배당 1위는 삼성전자 이재용',
 "금감원, 동양생명 '배당'·삼성화재 '성과급' 경영유의 조치",
 "네오위즈, 하반기 퀀텀 점프 기대…목표주가 '상향'-삼성",
 '녹십자 \'장중 주가 급락\'...삼성증권 "올해 실적 살펴야"',
 '당국 압박에 한국투자·삼성·KB증권, 신용융자 이자율 인하...미래에셋·메리츠 곧 인하',
 '대신증권 “엠씨넥스 목표주가 하향, 삼성전자 스마트폰 부진에 악영향”',
 '대신증권 “인터플렉스 목표주가 하향, 고객사 삼성전자 스마트폰 부진”',
 '두나무 증권플러스 비상장, 삼성증권 기업분석 리포트 서비스 제공',
 "두나무, '증권플러스 비상장'에 삼성증권 분석 리포트 게재",
 '레인보우로보틱스로 주목받는 삼성이 투자한 소부장 기업들....주가는 제각각·실적은↑',
 "미 긴축 장기화 우려에 삼성전자·SK하이닉스 주가 '흔들'",
 "미래에셋, 지난해 '고객 경영' 관심도 톱…KB·삼성증권 뒤이어",
 "미래에셋증권, '고객 경영' 관심도 1위…KB·삼성증권 뒤이어",
 '미래에셋증권, 삼성전자 ELW 등 175개 종목 신규 상장',
 "미래에셋증권, 지난해 '고객 경영' 관심도 1위…KB·삼성증권 순",
 "미래에셋증권, 지난해 '고객 경영' 관심도 톱…KB·삼성증권 뒤이어",
 '미래에셋증권, 지난해 ‘고객 경영’ 관심도 1위…KB·삼성증권 순',
 '미래컴퍼니 주가 26%↑ 이재용 삼성SDI 방문',
 '미래컴퍼니 주가 장중 상한가, 삼성 의료로봇 기업 인수 소문에',
 '바닥이 가깝다…삼성전자, 악재보다 호재에 민감할 시기-KB증권',
 "반도체 수급 개선 빨라진다…삼성전자 주가 흐름 '긍정적'-KB",
 "범상찮은 '챗GPT' 신드롬…삼성전자‧SK하이닉스 주가 기지개 켜나",
 '삼성 독점계약 끝났다… 증권사 각축장 된 美 주식 주간거래 서비스',
 '삼성 오너 일가, 주식 담보로 약 2조원 빌렸다…홍라희 8500억원·이부진 6500억원',
 '삼성FN리츠 공동주관사, 한투·NH·KB증권',
 '삼성FN리츠 증권신고서 제출...4월 초 상장 목표',
 '삼성FN리츠 증권신고서 제출...4월초 상장 목표',
 '삼성FN리츠 증권신고서 제출…4월 초 상장',
 '삼성FN리츠 증권신고서 제출…4월 초 상장 예정',
 '삼성FN리츠 증권신고서 제출…4월초 상장 예정',
 '삼성FN리츠, 증권신고서 제출...4월 초 상장 예정',
 '삼성FN리츠, 증권신고서 제출···4월 초 상장 예정',
 '삼성FN리츠, 증권신고서 제출…4월 상장 목표',
 '삼성FN리츠, 증권신고서 제출…4월 초 상장',
 '삼성FN리츠, 증권신고서 제출…4월초 상장 예정',
 '삼성FN리츠, 증권신고서 제출…삼성금융그룹 최초 공모 상장 리츠',
 '삼성FN리츠, 증권신고서 효력 발생...4월 코스피 상장',
 '삼성FN리츠, 증권신고서 효력 발생···공모 절차 본격 돌입',
 '삼성FN리츠, 증권신고서 효력 발생… 4월 상장 목표',
 '삼성FN리츠, 증권신고서 효력 발생…4월 상장',
 '삼성FN리츠, 증권신고서 효력 발생…4월 중 유가증권시장 상장 예정',
 '삼성FN리츠, 증권신고서 효력 발생…공모 절차 돌입',
 '삼성FN리츠, 증권신고서 효력 발생…내달 27~28일 일반공모',
 '삼성FN리츠, 증권신고서 효력 발생…오는 4월 코스피 상장',
 '삼성SDS 주가 장중 하락폭 키워, 삼성 오너가 이서현 지분 매각 영향',
 "삼성SDS, 삼성오너일가 상속세 납부 이슈에 주가 '직격탄' 맞은 까닭은",
 '삼성家 덮친 상속세…동생 이서현도 주식 몽땅 팔았다',
 '삼성家 상속세 골머리···이서현, 삼성SDS 주식 다 팔았다',
 '삼성家 이서현, 삼성SDS 주식 전량 매도…"상속세 납부"',
 '삼성家 이서현, 삼성SDS 주식 전량 매도…"상속세 납부용"',
 '삼성家 이서현, 삼성SDS 주식 전량 매도…상속세 납부 목적',
 '삼성家 이서현, 삼성SDS 주식 전량 매도…상속세 납부용',
 '삼성家 이서현, 삼성SDS 주식 전량 매도한다…“상속세 납부용”',
 '삼성家 이서현, 상속세 납부 위해 삼성SDS 주식 전량 매도',
 '삼성家 차녀, 삼성SDS 보유 주식 전량 매도… “왜?”',
 '삼성家, 상속세 마련 속도…이서현, 삼성SDS 주식 전량 매각',
 '삼성證 "3.0 시대 연 에스엠, 올해 실적 호조 전망…목표주가 상향"',
 '삼성證 “크래프톤, 신작 없어 주가 상승 제한… 투자의견 중립”',
 "삼성證·블루오션 독점 끝났다…증권사 '미국주식 주간거래' 포문",
 '삼성가 이서현, 삼성SDS 주식 전량 매도...상속세 납부 목적',
 '삼성가 이서현, 삼성SDS 지분 전량 매도···2조4000억 상속세 납부 목적',
 '삼성공조 주가 돌연 뜀박질...지루한 횡보장세에서 반발매수 유입',
 '삼성공조, 주당 80원 현금배당 결정',
 '삼성금융 공모상장 리츠...삼성FN리츠, 증권신고서 제출',
 "삼성금융그룹 첫 리츠 '삼성FN리츠', 증권신고서 제출",
 '삼성금융그룹 최초 공모 상장 리츠 ‘삼성FN리츠’ 증권신고서 제출…4월 초 상장 예정',
 '삼성물산 "5년간 3조 규모 자사주 소각한다"…주가 \'들썩\'',
 '삼성물산 "향후 3년간 최소 배당 2000원 유지"',
 '삼성물산 3조 자사주 전량 소각 소식에 기관 순매수 1위',
 '삼성물산 공매도 7만건 이상 증가…자사주 소각·배당정책 발표',
 '삼성물산 엇갈린 주가 전망…“가치제고 기대” vs “지켜봐야”',
 '삼성물산 자사주 전량 소각… 배당수익의 최대 70% 주주에 환원',
 '삼성물산 주가 상승, 3조원 규모 자사주 소각',
 '삼성물산 주가 장중 강세, 3조 규모 자사주 소각 및 주주환원 발표 영향',
 "삼성물산 주가 하락, 증권가 전망 엇갈려 '목표가 하향'",
 '삼성물산 파격적 주주환원책...‘만년 저평가’ 지주사 주가 깨워낼까?',
 '삼성물산, 3조 규모 자사주 소각 발표로 주가 6%대 강세',
 '삼성물산, 시가 3조 자사주 5년 내 매각 결정… "주당 배당 2000원 유지"',
 '삼성물산, 자사주 13% 5년간 분할 소각..최소 2000원 배당',
 '삼성물산, 자사주 소각·배당정책 발표에 5% 강세',
 '삼성물산, 자사주 소각·배당정책 발표에 강세(종합)',
 '삼성물산, 주가 상승... 3조원 규모 자사주 분할소각 결정',
 "삼성물산, 초강력 주주환원책에 주가 '화답'",
 "삼성물산, 향후 3년간 최소 배당 2000원 유지…5년간 자사주 '전량' 소각",
 '삼성베트남증권투자신탁·KB베트남포커스펀드, 베트남 공안당국 조사 받아…수출입은행 주가조작 연루 의혹',
 "삼성생명 실적 후폭풍…목표 배당성향 낮추자 투자자 '부글부글'",
 '삼성생명, 배당성향 최대 45% 목표...총주주환원율은 향후 발표',
 '삼성생명, 배당성향 최대 45% 유지',
 '삼성생명, 순익 개선에도 배당 동결…왜?',
 '삼성생명, 안정적인 배당 확대 의지 확인…목표가↑ [현대차증권]',
 '삼성생명, 영업익 감소에도 배당 유지…오너가 짭짤',
 '삼성생명, 의결권 제한 주식 비중 2년 새 8%p↑…대기업 상장사 중 3위',
 '삼성생명, 작년 순익 1.6조원···"향후 배당성향 35~45%"',
 '삼성생명, 중기 배당 목표 제시',
 "삼성에피스 파트너 '카더라'에 국내 CMO 주가 출렁",
 '삼성엔지니어링, 신규 수주 파이프라인 확대 [한화투자증권]',
 '삼성운용 시총·배당수익 톱5 종목 투자 ETF, 연초 이후 순자산 7000억원 유입',
 '삼성자산운용  KODEX Top5Plus TR ETF, 국내 주식형 ETF 중 연초 이후 순자산 유입 1위',
 "삼성자산운용 'KODEX Top5Plus TR ETF', 국내 주식형 ETF 순자산 유입 1위",
 '삼성자산운용 KODEX Top5Plus TR ETF 국내 주식형 ETF 중 연초 순자산 유입 1위',
 "삼성전자 '로봇 인재' 육성 소식에 주가 급등한 기업은",
 '삼성전자 3년만의 특별배당, 내년엔 어렵다…"재원 부족"',
 '삼성전자 SK하이닉스 주가 장중 약세, 미국 긴축흐름 연장 우려에 매도세',
 '삼성전자 감산 없었다… 주가 조정 시 매수해야 [이베스트투자증권]',
 "삼성전자 감산 이슈에 600만 주주 '철렁'...증권가는 7만 전자 시선",
 '삼성전자 목표주가, 6만5천원서 8만원으로 상향조정...대신증권',
 "삼성전자 주가 ‘반도체 사실상 감산’ 효과 기대감, 증권가 '8만전자' 낙관도",
 "삼성전자 주가 뛰자 삼성그룹주펀드 '훨훨'",
 '삼성전자 주가 상승, KB證 "챗GPT, 미래 메모리 수요 긍정적 요인"',
 "삼성전자 주가 상승, 삼성물산 자사주 소각 '3조원 규모'",
 '삼성전자 주가 상승, 챗gpt 미래 메모리 수요 긍정적',
 "삼성전자 주가 상승론 '솔솔'…목표주가 상향 잇달아",
 "삼성전자 주가 소폭 하락세, '6만 전자' 이후 전망은?",
 "삼성전자 주가 약세 '1월 시총 33조 늘었다'",
 '삼성전자 주가 하락, 기관 매도에 코스피지수↓',
 '삼성전자 주가 하락세, 미국 긴축기조 연장 전망',
 "삼성전자 훈풍?...맥스트 · 엔피 · 디어유 '장중 주가 껑충'",
 '삼성전자, 3분기부터 실적 회복…목표가 8만원 유지-KB증권',
 '삼성전자, 8만전자되나..대신證 목표주가↑',
 '삼성전자, ‘8만전자’ 되나...증권가 “반도체 상승사이클 진입”',
 '삼성전자, 목표주가 8만원 유지…설비투자 전략 영향-이베스트',
 '삼성전자, 하반기 주가 8만원 간다...“연중 실적 점진 개선될 것”',
 '삼성전자·SK하이닉스 주가 상승, 엔비디아 4분기 호실적에 반도체 관련주 수혜',
 "삼성전자·SK하이닉스, 주가 흐름 '멈칫'…이유가?",
 '삼성전자ㆍSK하이닉스 \'흔들\'..."삼성전자 6만원 무너지면 공격적 매수"',
 '삼성전자ㆍSK하이닉스ㆍ삼성SDIㆍ에코프로ㆍLG전자 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍSK하이닉스ㆍ아모레퍼시픽ㆍ카카오ㆍOCI 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍSK하이닉스ㆍ에스엠ㆍ삼성SDIㆍ에코프로 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍSK하이닉스ㆍ현대차ㆍ에코프로비엠ㆍ현대두산인프라코어 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍ에코프로비엠ㆍ한화솔루션ㆍSAMG엔터ㆍ이마트 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍ현대차ㆍ기아ㆍ현대제철ㆍ에코프로비엠 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍ현대차ㆍ에코프로ㆍSK하이닉스ㆍ기아 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성전자ㆍ현대차ㆍ에코프로ㆍ현대모비스ㆍ한화에어로스페이스 외국인 순매수 거래 활발...추정 기업가치는?',
 '삼성중공업 공매도 100만건 이상 급증…주가 하락세',
 '삼성중공업 주가 소극적 움직임, 스마트 조선소 시스템 적용 속도',
 '삼성증권 "\'삼성증권 코인\' 사기 주의하세요"',
 '삼성증권 "CATL 전기차 배터리 가격 인하, 경쟁사 단기적 영향 크지 않아"',
 '삼성증권 "LG, 제한적 다운사이드 리스크·매력적인 배당수익률"',
 '삼성증권 "美 주식 주간 거래하면 커피 선물 드려요"',
 '삼성증권 "강원랜드, 예상보다 방문객수 회복 더뎌…목표가↓"',
 '삼성증권 "네이버, 목표주가 올린다"',
 '삼성증권 "미국주식 주간거래 첫 거래하면 커피기프티콘 드려요"',
 '삼성증권 "밤샘투자 하지 마세요"…美 주식, 주간·애프터마켓 거래 이벤트',
 '삼성증권 "삼성화재, 위험손해율 개선세 돋보여"',
 '삼성증권 "에코프로비엠, 올해 캐파증설·풀가동...목표가↑"',
 '삼성증권 "카카오, 카톡 개편·점진적 경기 회복…목표주가↑"',
 '삼성증권 "투자시장 신인류 \'디지털 부유층\' 고객 선도한다"',
 '삼성증권 "한국가스공사, 해외사업 호조로 어닝서프라이즈 "',
 '삼성증권 "해외선물 거래하고 기프티콘 받으세요"',
 '삼성증권 ‘디지털 부유층’ 특화서비스 출시',
 '삼성증권 ‘디지털 부유층’대상… 신속한 정보·자문 서비스 확대',
 '삼성증권 ‘연금저축·IRP 페스타’ 이벤트',
 '삼성증권 “HMM, 예상 밖 선전...목표가 3만원”',
 '삼성증권 “원익IPS 목표주가 하향, 낸드와 올레드 장비 수요 회복 더뎌”',
 '삼성증권 美 주식 주간거래 독점계약 만료...증권가, 서학개미 유치 경쟁 본격화',
 '삼성증권 등 증권업계도 금리인하 대열에',
 '삼성증권 회사채 수요예측 부진…증권채 흥행 멈추나',
 "삼성증권, '나스닥100·러셀2000' 등 해외지수선물 거래서비스",
 "삼성증권, '디지털 부유층' 고객 공략 강화",
 "삼성증권, '디지털 부유층' 고객 사로잡는다",
 "삼성증권, '디지털 부유층' 고객 선도 나서",
 "삼성증권, '디지털 부유층' 공략... 'S.Lounge'로 고객 선도",
 "삼성증권, '디지털 부유층' 대두…맞춤형 서비스 제공 박차 [증권오늘]",
 "삼성증권, '디지털 부유층' 대상 자산관리 서비스 강화",
 "삼성증권, '밤샘투자는 BYE' 미국주식 주간거래/애프터마켓 거래 이벤트",
 "삼성증권, '밤샘투자는 BYE' 미국주식 주간거래·애프터마켓 거래 이벤트",
 "삼성증권, '밤샘투자는 BYE' 주간거래 이벤트 진행",
 "삼성증권, '온라인으로 1억이상 투자' 디지털 고객 잡는다",
 "삼성증권, '해외선물 거래' 서비스 오픈",
 "삼성증권, '해외선물 거래' 이벤트 진행",
 "삼성증권, '해외지수 선물' 거래 서비스 시작",
 '삼성증권, 23일부터 신용융자 이자율 인하',
 '삼성증권, 23일부터 신용융자 일부 구간 이자율 인하',
 "삼성증권, 23일부터 신용융자이자율 '인하'…최대 0.4%p↓",
 "삼성증권, 3월 말까지 '미국주식 거래' 이벤트",
 "삼성증권, 3월 말까지 '미국주식 거래' 이벤트 [증권오늘]",
 "삼성증권, 4Q 순영업수익 부진으로 '어닝쇼크'…주가도 약세",
 '삼성증권, 4분기 건전성 관리 빛났다…실적개선 기대감↑',
 '삼성증권, YTN 매각 주관사 철회키로…"하이브 자문에 집중"',
 '삼성증권, `밤샘 투자는 Bye` …미국주식 주간·애프터마켓 거래 이벤트',
 '삼성증권, `억대 온라인 투자` 엄지족 서비스 개편',
 '삼성증권, ‘디지털 부유층’ 고객 관리 강화…‘S라운지’ 선봬',
 '삼성증권, ‘디지털 부유층’ 대상 서비스 확대',
 '삼성증권, ‘디지털 부유층’ 서비스 고도화...투자정보까지 밀착지원',
 '삼성증권, ‘밤샘 투자 NO’ 美주식 주간거래·애프터마켓 거래 이벤트 진행',
 '삼성증권, ‘밤샘투자는 BYE’ 美주식 주간·애프터마켓 거래 이벤트',
 '삼성증권, ‘밤샘투자는 BYE’ 미국주식 주간거래·애프터마켓 거래 이벤트',
 '삼성증권, ‘해외 지수 선물’ 대고객 거래 서비스 오픈',
 '삼성증권, 美 주식 주간·애프터마켓 거래 이벤트 실시',
 '삼성증권, 美 주식 주간거래·애프터마켓 거래 이벤트',
 '삼성증권, 美 주식 주간거래·애프터마켓 이벤트 진행',
 '삼성증권, 美 지수 해외선물 서비스 출시',
 '삼성증권, 美주식 주간거래·애프터마켓 거래 이벤트',
 '삼성증권, 美주식 주간거래·애프터마켓 거래 이벤트 진행',
 '삼성증권, 美지수 해외선물 서비스 출시',
 '삼성증권, 고배당 기대 유효 [이베스트투자증권]',
 '삼성증권, 디지털 부유층 고객 맞춤 사업 강화',
 '삼성증권, 미국 주식 주간거래·애프터마켓 거래 이벤트',
 "삼성증권, 미국주식 '주간거래·애프터마켓 거래' 이벤트",
 '삼성증권, 미국주식 거래 신규 고객 이벤트',
 '삼성증권, 미국주식 주간거래 신규 고객 대상 이벤트 진행',
 '삼성증권, 미국주식 주간거래 이벤트',
 '삼성증권, 미국주식 주간거래/애프터마켓 거래 이벤트 진행',
 '삼성증권, 미국주식 주간거래·애프터마켓 거래 이벤트',
 '삼성증권, 미국주식 주간거래·애프터마켓 거래 이벤트 진행',
 '삼성증권, 미국주식 주간거래·애프터마켓 이벤트 실시',
 '삼성증권, 미국주식 주간거래‧애프터마켓 거래 이벤트',
 '삼성증권, 신규 고객 대상 미국주식 주간거래·애프터마켓 이벤트 진행',
 '삼성증권, 신용융자 이자율 0.1∼0.4%p 인하',
 '삼성증권, 신용융자 이자율 인하',
 '삼성증권, 신용융자 이자율 인하…23일부터 적용',
 '삼성증권, 신용융자 이자율 인하…증권업계도 내린다',
 '삼성증권, 신용융자 이자율 인하…최대 0.4%포인트 낮춰',
 '삼성증권, 신용융자 일부구간 이자율 인하',
 '삼성증권, 신재생·고령화·인력난 유망株 30개 담아',
 '삼성증권, 엄지족·고액자산 ‘디지털 부유층’ 서비스 고도화',
 '삼성증권, 오는 23일부터 신용융자 이자율 인하…최고 9.8%',
 '삼성증권, 올해 고배당 기대 유효-이베스트證',
 "삼성증권, 지난해 영업익 5786억 전년比 55.8%↓...'어닝 쇼크'",
 "삼성증권, 투자시장 신인류 '디지털 부유층' 공략 나선다",
 "삼성증권, 투자시장 신인류 '디지털 부유층' 대상 서비스 확대",

In [ ]:
# 뉴스 기사 인덱스 추출
idx = indices['“삼성전자 주식, 개인이 왜 사요?” 24년차 IT애널의 투자 조언[딥다이브]']; print(idx)

153

In [ ]:
# 선택한 뉴스 기사와 다른 뉴스 기사간 유사도 확인
sim_scores = list(enumerate(cosine_sim[idx]))

In [ ]:
# 유사도가 높은 순으로 뉴스 정렬
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

In [ ]:
# 유사도 높은 10개의 뉴스
sim_scores = sim_scores[1:11] # 0은 자기 자신일 것

# 가장 유사한 10개의 뉴스의 인덱스
news_indices = [i[0] for i in sim_scores]

# 유사한 뉴스 기사 제목 출력
df['제목'].iloc[news_indices]

# 코사인 유사도 기반 데이터 프레임
sim_df = pd.DataFrame(cosine_sim); sim_df

,0,1,2,3,4,5,6,7,8,9,...,747,748,749,750,751,752,753,754,755,756
0,1.000000,0.004509,0.024798,0.002651,0.003011,0.002429,0.119760,0.003270,0.002902,0.004129,...,0.003143,0.020857,0.003545,0.002969,0.107453,0.072779,0.002894,0.143071,0.003887,0.066517
1,0.004509,1.000000,0.010699,0.010784,0.202600,0.163436,0.124506,0.046360,0.127869,0.305682,...,0.044558,0.097448,0.014424,0.199769,0.013121,0.075663,0.041031,0.065299,0.055100,0.069154
2,0.024798,0.010699,1.000000,0.221287,0.167705,0.202797,0.063233,0.007760,0.006887,0.009797,...,0.007458,0.049491,0.008413,0.007045,0.007653,0.038427,0.135923,0.033580,0.009223,0.035121
3,0.002651,0.010784,0.221287,1.000000,0.007202,0.451510,0.124004,0.007821,0.114736,0.105312,...,0.007517,0.056419,0.140152,0.186003,0.202040,0.004107,0.006922,0.113177,0.009295,0.003754
4,0.003011,0.202600,0.167705,0.007202,1.000000,0.195793,0.007678,0.236891,0.007886,0.011218,...,0.008540,0.006010,0.009633,0.133410,0.008763,0.004666,0.007864,0.007373,0.010560,0.004265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,0.072779,0.075663,0.038427,0.004107,0.004666,0.003764,0.269800,0.005068,0.048705,0.100536,...,0.004871,0.171797,0.005494,0.004601,0.004998,1.000000,0.004485,0.137795,0.006023,0.913970
753,0.002894,0.041031,0.135923,0.006922,0.007864,0.006344,0.007380,0.059984,0.202087,0.037571,...,0.057652,0.005776,0.009259,0.007754,0.008422,0.004485,1.000000,0.007087,0.071293,0.004099
754,0.143071,0.065299,0.033580,0.113177,0.007373,0.005948,0.406521,0.008008,0.069624,0.084485,...,0.007696,0.084829,0.042384,0.035495,0.166160,0.137795,0.007087,1.000000,0.009517,0.125940
755,0.003887,0.055100,0.009223,0.009295,0.010560,0.008519,0.009911,0.344510,0.181644,0.050454,...,0.077421,0.007757,0.012434,0.010413,0.011310,0.006023,0.071293,0.009517,1.000000,0.005505
756,0.066517,0.069154,0.035121,0.003754,0.004265,0.003440,0.246589,0.004632,0.044514,0.091887,...,0.004452,0.157017,0.005021,0.004205,0.004568,0.913970,0.004099,0.125940,0.005505,1.000000

In [ ]:
# Boolean Index 만들기
sim_boolean = sim_df > 0.5; sim_boolean

,0,1,2,3,4,5,6,7,8,9,...,747,748,749,750,751,752,753,754,755,756
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
753,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
754,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
755,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
756,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [ ]:
# 유사도 0.5가 넘는 게시글이 10개 이상 있는 경우
sim_boolean.sum() >= 10

0       True
1      False
2      False
3      False
4       True
       ...
752     True
753    False
754     True
755    False
756     True
Length: 757, dtype: bool

In [ ]:
# 10개 이상 있는 게시글이 몇 개나 있을까?
sum(sim_boolean.sum() >= 10)

484

In [ ]:
# 유사도가 0.5 이상인 뉴스의 인덱스 확인해보기
sim_df[sim_boolean.sum() >= 10].index

Int64Index([  0,   4,  10,  14,  17,  21,  30,  34,  36,  40,
            ...
            737, 738, 739, 744, 746, 747, 748, 752, 754, 756],
           dtype='int64', length=484)

In [ ]:
# 유사도가 0.4 이상인 게시글은 얼마나 유사할까?
idx_list = sim_df[0][sim_df[0] > 0.4].index
df.iloc[idx_list,:]

,제목,언론사,날짜,URL,네이버뉴스_URL,단어,제목_전처리
0,에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로비, 엠, 하이닉스, 삼성, 셀트리온, 현대, 로템, 외국인, 매수, ...",에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발 ...
31,외국인 삼성전자 SK하이닉스 집중매수...에코프로비엠 엘앤에프 에코프로 폭등,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[외국인, 삼성, 전자, 하이닉스, 집중, 매수, 에코, 프로비, 엠, 엘앤, 에프...",외국인 삼성전자 SK하이닉스 집중매수 에코프로비엠 엘앤에프 에코프로 폭등
34,삼성전자ㆍSK하이닉스ㆍ아모레퍼시픽ㆍ카카오ㆍOCI 외국인 순매수 거래 활발...추정 ...,핀포인트뉴스,2023.02.03.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 하이닉스, 아모레퍼시픽, 카카오, 외국인, 매수, 거래, 활발, 추...",삼성전자ㆍSK하이닉스ㆍ아모레퍼시픽ㆍ카카오ㆍOCI 외국인 순매수 거래 활발 추정 ...
55,삼성전자ㆍ현대차ㆍ에코프로ㆍSK하이닉스ㆍ기아 외국인 순매수 거래 활발...추정 기업가치는?,핀포인트뉴스,2023.02.04.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 현대차, 에코, 프로, 하이닉스, 기아, 외국인, 매수, 거래, 활...",삼성전자ㆍ현대차ㆍ에코프로ㆍSK하이닉스ㆍ기아 외국인 순매수 거래 활발 추정 기업가치는
131,에코프로비엠ㆍ에코프로ㆍ삼성SDIㆍ한화에어로스페이스ㆍKT 외국인 순매수 거래 활발.....,핀포인트뉴스,2023.02.07.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로비, 엠, 에코, 프로, 삼성, 한화, 에어로, 스페이스, 외국인, 매...",에코프로비엠ㆍ에코프로ㆍ삼성SDIㆍ한화에어로스페이스ㆍKT 외국인 순매수 거래 활발 ...
151,에코프로ㆍSK하이닉스ㆍ삼성전자ㆍ에코프로비엠ㆍLG화학 외국인 순매수 거래 활발...추...,핀포인트뉴스,2023.02.08.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로, 하이닉스, 삼성, 전자, 에코, 프로비, 엠, 화학, 외국인, 매수...",에코프로ㆍSK하이닉스ㆍ삼성전자ㆍ에코프로비엠ㆍLG화학 외국인 순매수 거래 활발 추...
168,삼성전자ㆍSK하이닉스ㆍ삼성SDIㆍ에코프로ㆍLG전자 외국인 순매수 거래 활발...추정...,핀포인트뉴스,2023.02.09.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 하이닉스, 삼성, 에코, 프로, 전자, 외국인, 매수, 거래, 활발...",삼성전자ㆍSK하이닉스ㆍ삼성SDIㆍ에코프로ㆍLG전자 외국인 순매수 거래 활발 추정...
185,에코프로비엠ㆍ삼성전자ㆍ포스코케미칼ㆍ에코프로ㆍ삼성SDI 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.10.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로비, 엠, 삼성, 전자, 포스코, 케미칼, 에코, 프로, 삼성, 외국인...",에코프로비엠ㆍ삼성전자ㆍ포스코케미칼ㆍ에코프로ㆍ삼성SDI 외국인 순매수 거래 활발 ...
226,삼성전자ㆍSK하이닉스ㆍ에스엠ㆍ삼성SDIㆍ에코프로 외국인 순매수 거래 활발...추정 ...,핀포인트뉴스,2023.02.11.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 하이닉스, 에스엠, 삼성, 에코, 프로, 외국인, 매수, 거래, 활...",삼성전자ㆍSK하이닉스ㆍ에스엠ㆍ삼성SDIㆍ에코프로 외국인 순매수 거래 활발 추정 ...
325,에스엠ㆍ엘앤에프ㆍ삼성SDIㆍ현대모비스ㆍ현대차 외국인 순매수 거래 활발...추정 기업...,핀포인트뉴스,2023.02.15.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에스엠, 엘앤, 에프, 삼성, 현대, 모비스, 현대차, 외국인, 매수, 거래, 활...",에스엠ㆍ엘앤에프ㆍ삼성SDIㆍ현대모비스ㆍ현대차 외국인 순매수 거래 활발 추정 기업...
389,삼성전자ㆍ에코프로비엠ㆍ한화솔루션ㆍSAMG엔터ㆍ이마트 외국인 순매수 거래 활발...추...,핀포인트뉴스,2023.02.16.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 에코, 프로비, 엠, 한화, 솔루션, 엔터, 이마트, 외국인, 매수...",삼성전자ㆍ에코프로비엠ㆍ한화솔루션ㆍSAMG엔터ㆍ이마트 외국인 순매수 거래 활발 추...
415,삼성전자ㆍ현대차ㆍ기아ㆍ현대제철ㆍ에코프로비엠 외국인 순매수 거래 활발...추정 기업가치는?,핀포인트뉴스,2023.02.17.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 현대차, 기아, 현대, 제철, 에코, 프로비, 엠, 외국인, 매수,...",삼성전자ㆍ현대차ㆍ기아ㆍ현대제철ㆍ에코프로비엠 외국인 순매수 거래 활발 추정 기업가치는
460,삼성전자ㆍSK하이닉스ㆍ현대차ㆍ에코프로비엠ㆍ현대두산인프라코어 외국인 순매수 거래 활발...,핀포인트뉴스,2023.02.18.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 하이닉스, 현대차, 에코, 프로비, 엠, 현대, 두산인프라코어, 외...",삼성전자ㆍSK하이닉스ㆍ현대차ㆍ에코프로비엠ㆍ현대두산인프라코어 외국인 순매수 거래 활발...
599,삼성전자ㆍ현대차ㆍ에코프로ㆍ현대모비스ㆍ한화에어로스페이스 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.24.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 전자, 현대차, 에코, 프로, 현대, 모비스, 한화, 에어로, 스페이스, ...",삼성전자ㆍ현대차ㆍ에코프로ㆍ현대모비스ㆍ한화에어로스페이스 외국인 순매수 거래 활발 ...
744,과대낙폭 반발매수 다우ㆍ나스닥 훨훨...테슬라도 상승 삼성SDIㆍ에코프로비엠 등 훈풍?,핀포인트뉴스,2023.02.28.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[과대, 낙폭, 반발, 매수, 다우, 나스닥, 훨훨, 테슬라, 상승, 삼성, 에코,...",과대낙폭 반발매수 다우ㆍ나스닥 훨훨 테슬라도 상승 삼성SDIㆍ에코프로비엠 등 훈풍

In [ ]:
# 특정 유사도 이상의 뉴스 토픽 묶기

idx_list = list(sim_df[sim_boolean.sum() >= 10].index)
cluster = []
pass_list = []
threshold = 0.25
id_idx = []
for i in idx_list:
    if i not in pass_list:
        idx = sim_df[i][sim_df[i] > threshold].index
        cluster.append(idx)
        pass_list.extend(list(idx))
        id_idx.append(i)
    else:
        pass

print(len(cluster))

25

In [ ]:
# 삼성 주식 뉴스 토픽
samsung_df = df.iloc[id_idx,:].copy(); samsung_df

,제목,언론사,날짜,URL,네이버뉴스_URL,단어,제목_전처리
0,에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발......,핀포인트뉴스,2023.02.02.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[에코, 프로비, 엠, 하이닉스, 삼성, 셀트리온, 현대, 로템, 외국인, 매수, ...",에코프로비엠ㆍSK하이닉스ㆍ삼성SDIㆍ셀트리온ㆍ현대로템 외국인 순매수 거래 활발 ...
4,"삼성생명, 영업익 감소에도 배당 유지…오너가 짭짤",딜사이트,2023.02.02.,https://dealsite.co.kr/articles/98328,NaN,"[삼성, 생명, 영업, 익, 감소, 배당, 유지, 너, 짤]",삼성생명 영업익 감소에도 배당 유지 오너가 짭짤
10,"[특징주] 삼성물산, 안정적 실적과 주주가치 제고에도 주가 약세",글로벌이코노믹,2023.02.02.,http://www.g-enews.com/ko-kr/news/article/news...,NaN,"[특징, 주, 삼성, 물산, 안정, 실적, 주주, 가치, 고, 주가, 약세]",특징주 삼성물산 안정적 실적과 주주가치 제고에도 주가 약세
17,"코스피, 외인 매수에 2,450선 상승...삼성전자 1%대 '오르막'",뉴스투데이,2023.02.02.,https://www.news2day.co.kr/article/20230202500118,NaN,"[코스피, 외인, 매수, 선, 상승, 삼성, 전자, 오르막]",코스피 외인 매수에 2 450선 상승 삼성전자 1 대 오르막
30,[증시] 미국 FOMC 안도감에 코스피 0.8% 상승 마감…외인 순매수 상위 종목은...,톱스타뉴스,2023.02.02.,http://www.topstarnews.net/news/articleView.ht...,NaN,"[증시, 미국, 안도, 감, 코스피, 상승, 마감, 외인, 매수, 상위, 종목, 삼...",증시 미국 FOMC 안도감에 코스피 0 8 상승 마감 외인 순매수 상위 종목은...
36,"삼성전자, 8만전자되나..대신證 목표주가↑",파이낸셜뉴스언론사 선정,2023.02.03.,http://www.fnnews.com/news/202302030446448830,https://n.news.naver.com/mnews/article/014/000...,"[삼성, 전자, 대신, 목표, 주가]",삼성전자 8만전자되나 대신證 목표주가
51,"[데이터로 보는 증시]NAVER·삼성전자, 기관·외국인 코스피 순매수 1위(2월 3일)",서울경제,2023.02.03.,https://www.sedaily.com/NewsView/29LLVQU0HF,https://n.news.naver.com/mnews/article/011/000...,"[데이터, 증시, 삼성, 전자, 기관, 외국인, 코스피, 매수, 위]",데이터로 보는 증시 NAVER 삼성전자 기관 외국인 코스피 순매수 1위 2월 3일
53,"삼성전자 주가 ‘반도체 사실상 감산’ 효과 기대감, 증권가 '8만전자' 낙관도",비즈니스포스트,2023.02.03.,https://www.businesspost.co.kr/BP?command=arti...,NaN,"[삼성, 전자, 주가, 반도체, 사실, 감산, 효과, 대감, 증권, 낙관]",삼성전자 주가 반도체 사실상 감산 효과 기대감 증권가 8만전자 낙관도
60,"“챗GPT야, 삼성전자 주가 계속 오르니?”…어닝쇼크가 ‘위기’ 아니란 3가지 이유...",헤럴드경제언론사 선정,2023.02.05.,http://news.heraldcorp.com/view.php?ud=2023020...,https://n.news.naver.com/mnews/article/016/000...,"[챗, 삼성, 전자, 주가, 계속, 어닝쇼크, 위기, 가지, 이유, 놈, 챗]",챗GPT야 삼성전자 주가 계속 오르니 어닝쇼크가 위기 아니란 3가지 이유...
62,"[투자주체 매매동향] 외국인투자자, 한주간 삼성전자 2580억 사들이며 순매수 1위",핀포인트뉴스,2023.02.05.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[투자, 주체, 매매, 동향, 외국인투자, 주간, 삼성, 전자, 매수, 위]",투자주체 매매동향 외국인투자자 한주간 삼성전자 2580억 사들이며 순매수 1위
69,삼성증권: NAVER·솔루엠·POSCO홀딩스,서울파이낸스,2023.02.06.,http://www.seoulfn.com/news/articleView.html?i...,NaN,"[삼성, 증권, 솔루엠, 홀딩스]",삼성증권 NAVER 솔루엠 POSCO홀딩스
76,"삼성증권, 해외지수선물 고객 거래 서비스 오픈",세계비즈,2023.02.06.,http://www.segyebiz.com/newsView/2023020650311...,NaN,"[삼성, 증권, 해외, 지수선물, 고객, 거래, 서비스, 오픈]",삼성증권 해외지수선물 고객 거래 서비스 오픈
154,삼성證·블루오션 독점 끝났다…증권사 '미국주식 주간거래' 포문,연합인포맥스,2023.02.08.,http://news.einfomax.co.kr/news/articleView.ht...,NaN,"[삼성, 블루, 오션, 독점, 증권사, 미국, 주식, 주간, 거래, 포문]",삼성證 블루오션 독점 끝났다 증권사 미국주식 주간거래 포문
169,삼성중공업 공매도 100만건 이상 급증…주가 하락세,핀포인트뉴스,2023.02.09.,https://www.pinpointnews.co.kr/news/articleVie...,NaN,"[삼성, 중공업, 공매도, 이상, 급증, 주가, 하락, 세]",삼성중공업 공매도 100만건 이상 급증 주가 하락세
175,이서현 주식 전량 매각 소식에…삼성 SDS 장 초반 약세,머니투데이,2023.02.09.,http://news.mt.co.kr/mtview.php?no=20230209091...,https://n.news.naver.com/mnews/article/008/000...,"[이서현, 주식, 전량, 매각, 소식, 삼성, 장, 초반, 약세]",이서현 주식 전량 매각 소식에 삼성 SDS 장 초반 약세
202,삼성家 덮친 상속세…동생 이서현도 주식 몽땅 팔았다,SBS Biz언론사 선정,2023.02.10.,https://biz.sbs.co.kr/article_hub/20000102719?...,https://n.news.naver.com/mnews/article/374/000...,"[삼성, 친, 상속세, 동생, 이서현, 주식, 몽땅]",삼성家 덮친 상속세 동생 이서현도 주식 몽땅 팔았다
244,"증권플러스 비상장, 삼성증권 기업 분석 리포트 서비스 제공",경향게임스,2023.02.13.,https://www.khgames.co.kr/news/articleView.htm...,NaN,"[증권, 플러스, 비상, 삼성, 증권, 기업, 분석, 리포트, 서비스, 제공]",증권플러스 비상장 삼성증권 기업 분석 리포트 서비스 제공
250,[마켓인]삼성FN리츠 증권신고서 제출…4월 초 상장,이데일리,2023.02.13.,http://www.edaily.co.kr/news/newspath.asp?news...,https://n.news.naver.com/mnews/article/018/000...,"[마켓, 삼성, 리츠, 증권, 신고, 제출, 초, 상장]",마켓인 삼성FN리츠 증권신고서 제출 4월 초 상장
393,"삼성물산, 자사주 13% 5년간 분할 소각..최소 2000원 배당",스마트투데이,2023.02.16.,https://www.smartcitytoday.co.kr/news/articleV...,NaN,"[삼성, 물산, 자, 사주, 분할, 소각, 최소, 배당]",삼성물산 자사주 13 5년간 분할 소각 최소 2000원 배당
432,"삼성증권, 신용융자 일부구간 이자율 인하",브릿지경제,2023.02.17.,https://www.viva100.com/main/view.php?key=2023...,NaN,"[삼성, 증권, 신용, 융자, 일부, 구간, 이자율, 인하]",삼성증권 신용융자 일부구간 이자율 인하
504,유진투자증권 '예드자문형 랩 삼성전자' 출시,서울와이어,2023.02.21.,http://www.seoulwire.com/news/articleView.html...,NaN,"[유진, 투자, 증권, 드, 자문, 랩, 삼성, 전자, 출시]",유진투자증권 예드자문형 랩 삼성전자 출시
521,삼성페이·네이버페이 맞손…지니틱스 주가 상승,스포츠한국,2023.02.21.,https://sports.hankooki.com/news/articleView.h...,NaN,"[삼성, 페이, 네이버, 페이, 손, 지니, 스, 주가, 상승]",삼성페이 네이버페이 맞손 지니틱스 주가 상승
548,"“삼성화재, 이익안전성 지속 전망…배당수익률 7% 달할 것”",이투데이,2023.02.22.,https://www.etoday.co.kr/news/view/2224194,NaN,"[삼성, 화재, 이익, 안전성, 지속, 전망, 배당, 수익률, 달, 것]",삼성화재 이익안전성 지속 전망 배당수익률 7 달할 것
615,[부고] 조제영(삼성증권 이사)씨 장인상,투데이코리아,2023.02.25.,http://www.todaykorea.co.kr/news/articleView.h...,NaN,"[부고, 영, 삼성, 증권, 이사, 씨, 장인상]",부고 조제영 삼성증권 이사 씨 장인상
691,"삼성증권, 투자시장 신인류 ‘디지털 부유층’ 특화서비스 출시",헤럴드경제,2023.02.27.,http://news.heraldcorp.com/view.php?ud=2023022...,https://n.news.naver.com/mnews/article/016/000...,"[삼성, 증권, 투자, 시장, 인류, 디지털, 부유, 층, 특, 서비스, 출시]",삼성증권 투자시장 신인류 디지털 부유층 특화서비스 출시

In [ ]:
import os
path = '/content/drive/MyDrive/딥다이브/2강'
filename = '삼성주가 이슈 클러스터링.csv'
samsung_df.to_csv(os.path.join(path, filename), index = False)